export interface VertiefungAbschnitt {
  titel: string;
  text: string;
}

export interface WeitereFrage {
  frage: string;
  antwort: string;
}

export interface LeistungThema {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  heroFrage: string;
  heroLead: string;
  heroImage: string;
  /** Beschreibt, was auf dem Hero-Bild zu sehen ist (Alt-Text, deutsch). */
  heroImageAlt: string;
  problemUeberschrift: string;
  problemText: string;
  loesungUeberschrift: string;
  loesungPunkte: string[];
  /** Bild neben dem Problem-Abschnitt. Leer: die Vorlage zeigt heroImage. */
  problemBild?: string;
  problemBildAlt?: string;
  /** Bild neben dem Lösungs-Abschnitt. Leer: kein Bild, Text in innerer Lesespalte. */
  loesungBild?: string;
  loesungBildAlt?: string;
  vertiefungUeberschrift?: string;
  vertiefungAbschnitte?: VertiefungAbschnitt[];
  sekundaerBild?: string;
  sekundaerBildAlt?: string;
  bildVorher?: string;
  bildVorherAlt?: string;
  bildNachher?: string;
  bildNachherAlt?: string;
  boxTitel: string;
  ausEinerHandText: string;
  faqFrage: string;
  faqAntwort: string;
  weitereFragen?: WeitereFrage[];
  /** Interne Links auf verwandte Themen (2–3). Leer: kein Abschnitt. */
  verwandteThemen?: { href: string; text: string }[];
}

export const LEISTUNGEN_THEMEN: LeistungThema[] = [
  {
    slug: "komplettsanierung",
    title: "Komplettsanierung",
    metaTitle: "Komplettsanierung München – Haus & Wohnung | Renodex",
    metaDescription: "Alles auf einmal sanieren, ohne fünf Firmen selbst zu steuern? Renodex koordiniert alle Gewerke in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Komplettsanierung in München: Wie greifen alle Gewerke ineinander?",
    heroLead: "Sie haben ein älteres Haus oder eine Wohnung gekauft und wollen alles in einem Zug erneuern. Elektro, Sanitär, Heizung, Böden und Wände hängen dabei voneinander ab. Eingetragene Fachfirmen führen die Arbeiten aus. Renodex koordiniert Reihenfolge und Termine der Gewerke.",
    heroImage: "/images/optimized/komplettsanierung-elektro-sanitaer-boden-muenchen.webp",
    heroImageAlt: "Elektriker und Installateur arbeiten gleichzeitig bei einer Komplettsanierung",
    problemUeberschrift: "Warum wird eine Komplettsanierung so leicht unübersichtlich?",
    problemText: "Jedes Gewerk baut auf dem vorherigen auf. Der Elektriker muss fertig sein, bevor der Trockenbauer die Wand schließt. Der Estrich muss trocken sein, bevor der Boden kommt. Wer jede Firma einzeln beauftragt, koordiniert das selbst. Verschiebt sich ein Schritt, warten alle folgenden.",
    loesungUeberschrift: "Wie läuft eine Komplettsanierung mit Renodex ab?",
    loesungPunkte: [
      "Sie schicken Fotos, Grundriss und eine kurze Beschreibung des Vorhabens",
      "Renodex ordnet die nötigen Gewerke und ihre Reihenfolge",
      "Eingetragene Fachfirmen erstellen Angebote und führen die Arbeiten aus",
      "Ein Ansprechpartner stimmt Termine und Übergaben zwischen den Gewerken ab",
    ],
    vertiefungUeberschrift: "Was gehört zu einer Komplettsanierung?",
    vertiefungAbschnitte: [
      { titel: "In welcher Reihenfolge laufen die Gewerke?", text: "Am Anfang stehen Rückbau und die Prüfung auf Schadstoffe. Danach folgen die Leitungen für Elektro, Sanitär und Heizung, solange Wände und Böden offen sind. Trockenbau, Putz und Estrich schließen anschließend die Installationsebene. Fliesen, Bodenbeläge und Malerarbeiten kommen zum Schluss. So muss niemand fertige Flächen wieder öffnen." },
      { titel: "Worauf wird beim Rückbau im Altbau geachtet?", text: "In Gebäuden aus der Zeit vor 1993 können Fliesenkleber, Bodenbeläge oder Spachtelmassen Asbest enthalten. Ein Verdacht lässt sich nur mit einer Materialprobe im Labor klären. Bestätigt sich der Befund, wird die Asbestsanierung vor dem übrigen Rückbau eingeplant. Erst danach arbeiten die anderen Gewerke in den betroffenen Räumen." },
      { titel: "Was unterscheidet Komplettsanierung, Wohnungs- und Haussanierung?", text: "Die Wohnungssanierung umfasst die Gewerke innerhalb einer Wohnung. Die Haussanierung betrifft bei Renodex die Außenanlagen rund ums Gebäude. Die Komplettsanierung bündelt mehrere Bausteine zu einem Bauablauf, etwa Wohnung, Bad, Heizung und Elektro. Welche Bausteine Ihr Vorhaben braucht, zeigen Fotos, Grundriss und Ihre Beschreibung." },
    ],
    boxTitel: "Alle Gewerke in einem Bauablauf",
    ausEinerHandText: "Eine Komplettsanierung betrifft oft Haus und Wohnung zugleich. Sind Fassade oder Mauerwerksabdichtung Teil des Vorhabens, koordiniert Renodex sie auf Wunsch mit.",
    faqFrage: "Was kostet eine Komplettsanierung in München?",
    faqAntwort: "Das hängt von Fläche, Zustand und den beteiligten Gewerken ab. Einen Pauschalpreis gibt es deshalb nicht. Die Preisübersicht von Renodex nennt Richtpreise für einzelne Gewerke, etwa 800 bis 1.800 Euro je Quadratmeter für eine komplette Badsanierung. Verbindlich sind erst die schriftlichen Kostenvoranschläge der ausführenden Fachfirmen.",
    weitereFragen: [
      { frage: "Kann ich während einer Komplettsanierung in der Wohnung bleiben?", antwort: "Das hängt vom Umfang ab. Werden Bad, Küche und Leitungen gleichzeitig erneuert, ist ein vorübergehender Auszug meist die bessere Lösung. Bei raumweisen Abschnitten bleibt ein Teil der Wohnung nutzbar. Das wird vor Beginn mit Ihnen besprochen." },
      { frage: "Muss ich für jedes Gewerk eine eigene Anfrage stellen?", antwort: "Nein. Sie beschreiben das gesamte Vorhaben einmal über die digitale Anfrage. Renodex ordnet die nötigen Gewerke zu und stimmt die Angebote der beteiligten Fachfirmen aufeinander ab." },
      { frage: "Lassen sich auch nur zwei Gewerke kombinieren?", antwort: "Ja. Auch zwei Gewerke lassen sich gemeinsam koordinieren, etwa Trockenbau und Malerarbeiten nach einem Wasserschaden. Eine volle Sanierung ist dafür keine Voraussetzung." },
      { frage: "Gibt es Förderung für eine Komplettsanierung?", antwort: "Für energetische Maßnahmen wie Heizungstausch oder Dämmung gibt es die Bundesförderung für effiziente Gebäude, für Wohngebäude über KfW und BAFA. Der Antrag muss in der Regel vor Beginn gestellt sein. Die Bedingungen ändern sich. Maßgeblich ist der aktuelle Stand beim jeweiligen Förderträger." },
      { frage: "Wer führt die Arbeiten aus?", antwort: "Eingetragene Fachfirmen je Gewerk. Den Vertrag über die Bauleistung schließen Sie wahlweise mit Renodex, auch als Gesamtpaket zu einem Festpreis, oder direkt mit der ausführenden Fachfirma. Renodex koordiniert in beiden Fällen Termine und Reihenfolge der Gewerke." },
    ],
    verwandteThemen: [
      { href: "/leistungen/badsanierung", text: "Badsanierung" },
      { href: "/leistungen/elektroinstallation", text: "Elektroinstallation" },
      { href: "/leistungen/sanitaer", text: "Sanitär" },
      { href: "/leistungen/heizung", text: "Heizung erneuern" },
    ],
  },
  {
    slug: "haussanierung",
    title: "Haussanierung",
    metaTitle: "Außenanlagen München – Terrasse & Einfahrt | Renodex",
    metaDescription: "Terrasse uneben, Wasser läuft zum Haus? Renodex koordiniert die Sanierung von Terrasse, Einfahrt und Wegen in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Außenanlagen in München: Was gehört zur Sanierung rund ums Haus?",
    heroLead: "Terrasse, Einfahrt, Gartenwege und die Entwässerung rund ums Grundstück bilden ein eigenes Fachthema – unabhängig von Fassade oder Dach. Renodex koordiniert die Sanierung dieser Außenanlagen als eigenständiges Vorhaben oder im Zusammenhang mit einer Komplettsanierung.",
    heroImage: "/images/optimized/aussenanlagen-terrasse-pflaster-muenchen.webp",
    heroImageAlt: "Handwerker verlegt Terrassenplatten mit dem Gummihammer bei der Sanierung einer Außenanlage",
    problemUeberschrift: "Falsches Gefälle rächt sich erst mit der Zeit",
    problemText: "Terrassen und Einfahrten, die vor Jahrzehnten verlegt wurden, entwässern häufig nicht mehr richtig: Platten liegen uneben, Fugen sind ausgewaschen, und Regenwasser läuft in Richtung Haus statt davon weg. Wird nur die Optik erneuert und das Gefälle nicht mitgeplant, taucht das Problem nach der nächsten Sanierung wieder auf.",
    loesungUeberschrift: "Außenanlagen mit funktionierender Entwässerung",
    loesungPunkte: [
      "Prüfung von Gefälle und Entwässerung vor der Neugestaltung",
      "Terrassenbeläge, Einfahrtsbefestigung und Gartenwege abgestimmt",
      "Versickerung oder Ableitung nach den örtlichen Vorgaben geplant",
      "Anschlüsse an Sockel und Fassade wasserdicht ausgeführt",
    ],
    vertiefungUeberschrift: "Worauf kommt es bei der Sanierung von Terrasse und Einfahrt an?",
    vertiefungAbschnitte: [
      { titel: "Welches Gefälle braucht eine Terrasse oder Einfahrt?", text: "Befestigte Außenflächen brauchen in der Regel ein Mindestgefälle von etwa 2 bis 2,5 Prozent, damit Regenwasser zuverlässig abläuft und sich nicht vor der Fassade oder auf dem Belag staut. Wird eine bestehende Fläche neu verlegt, wird dieses Gefälle im Unterbau neu hergestellt, nicht nur an der Oberfläche kaschiert." },
      { titel: "Wohin darf das Regenwasser von Terrasse und Einfahrt abgeleitet werden?", text: "Niederschlagswasser soll nach den wasserrechtlichen Vorgaben möglichst ortsnah versickern statt in die Kanalisation zu laufen – das reduziert häufig auch die Niederschlagswassergebühr der Gemeinde. Ob eine Versickerung auf dem eigenen Grundstück möglich ist, hängt vom Bodenaufbau und den örtlichen Vorgaben der zuständigen Stadt- oder Gemeindeentwässerung ab, die vor der Planung geprüft werden." },
      { titel: "Warum ist der Anschluss an die Fassade bei Terrassen besonders wichtig?", text: "Im Übergang zwischen Terrasse oder Balkon und Fassade muss sichergestellt sein, dass kein Wasser hinter die Abdichtung oder in den Sockelbereich läuft. Ein zu geringer Abstand zwischen Belagoberkante und Fassadenanschluss zählt zu den häufigsten Ursachen für spätere Feuchteschäden am Mauerwerk und wird bei der Planung entsprechend berücksichtigt." },
    ],
    boxTitel: "Außenanlagen aus einer Hand koordiniert",
    ausEinerHandText: "Die Sanierung der Außenanlagen lässt sich eigenständig beauftragen oder mit anderen Gewerken wie Fassade oder Mauerwerksabdichtung kombinieren, wenn diese ohnehin Teil des Vorhabens sind – Renodex stimmt die Reihenfolge entsprechend ab.",
    faqFrage: "Wie lange dauert die Sanierung von Terrasse und Einfahrt?",
    faqAntwort: "Das hängt von der Fläche, dem gewählten Belag und dem Zustand des Unterbaus ab. Nach der digitalen Erstaufnahme über Foto oder Video nennt Renodex einen realistischen Zeitrahmen für das konkrete Vorhaben.",
    weitereFragen: [
      { frage: "Kann die Einfahrt saniert werden, ohne die Terrasse anzufassen?", antwort: "Ja, beide Flächen lassen sich unabhängig voneinander sanieren. Eine gemeinsame Planung lohnt sich vor allem, wenn Maschinen oder Material ohnehin auf das Grundstück müssen." },
      { frage: "Was passiert mit alten Platten oder Pflaster beim Rückbau?", antwort: "Der alte Belag wird aufgenommen, der Unterbau auf Tragfähigkeit und Gefälle geprüft und bei Bedarf neu hergestellt, bevor der neue Belag verlegt wird. Nur die Oberfläche auszutauschen, ohne den Unterbau zu prüfen, behebt bestehende Entwässerungsprobleme nicht." },
      { frage: "Braucht eine Versickerungsanlage im Garten eine Genehmigung?", antwort: "Das hängt von Art und Umfang der Anlage sowie den örtlichen Vorschriften ab. Renodex klärt das im Rahmen der Erstberatung mit den zuständigen Stellen ab, bevor die Umsetzung geplant wird." },
    ],

  },
  {
    slug: "wohnungssanierung",
    title: "Wohnungssanierung",
    metaTitle: "Wohnungssanierung München – Gewerke koordiniert | Renodex",
    metaDescription: "Wohnung gekauft oder Mieterwechsel? Renodex koordiniert Elektro, Sanitär, Böden und Malerarbeiten in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Wohnungssanierung in München: Was gehört alles dazu?",
    heroLead: "Eine Wohnungssanierung deckt bei Renodex alle Gewerke innerhalb der Wohnung ab: Elektro, Sanitär, Heizung, Böden, Trockenbau und Malerarbeiten – vom einzelnen Raum bis zur kompletten Wohnung. Ausgelöst wird sie häufig durch einen Eigentümerwechsel, eine Vermietung oder den Wunsch, veraltete Technik zeitgemäß zu ersetzen. Renodex saniert unter laufender Terminplanung und mit möglichst wenig Beeinträchtigung für die Bewohner.",
    heroImage: "/images/optimized/wohnungssanierung-trockenbau-altbau-muenchen.webp",
    heroImageAlt: "Handwerker setzt Gipskartonplatten bei der Sanierung einer Stadtwohnung",
    problemUeberschrift: "Alle Gewerke einer Wohnung, aber begrenztes Zeitfenster",
    problemText: "In einer Wohnung lässt sich selten monatelang bauen – oft müssen Elektro, Sanitär, Heizung, Böden und Malerarbeiten in einem klar begrenzten Zeitfenster fertig werden, während der Alltag weiterläuft oder ein Mieterwechsel ansteht.",
    loesungUeberschrift: "Alle Gewerke der Wohnung aus einer Planung",
    loesungPunkte: [
      "Klar terminierte Bauabschnitte statt offenem Zeitrahmen",
      "Elektro, Sanitär, Heizung, Böden, Trockenbau und Malerarbeiten aus einer Hand",
      "Abstimmung mit Eigentümer, Hausverwaltung oder Mieter",
      "Saubere Übergabe nach Fertigstellung",
    ],
    vertiefungUeberschrift: "Wie lange dauert eine Wohnungssanierung in München?",
    vertiefungAbschnitte: [
      { titel: "Wie lange dauert eine Wohnungssanierung?", text: "Die Dauer richtet sich nach Größe, Zustand und Umfang der Wohnung sowie danach, ob Bewohner während der Arbeiten ausziehen oder nicht. Eine Wohnung mit Elektro-Neuverkabelung, neuen Böden, Trockenbauarbeiten und Malerarbeiten braucht in der Regel mehr Vorlauf als eine reine Renovierung ohne Eingriff in die Gebäudetechnik. Nach der digitalen Erstaufnahme über Foto, Video oder Sprachnachricht wird ein realistischer Zeitrahmen für die konkrete Wohnung genannt, statt eine pauschale Wochenangabe." },
      { titel: "Welche Gewerke greifen bei einer Wohnungssanierung ineinander?", text: "Elektroinstallation, Sanitär, Heizung, Bodenverlegung, Trockenbau und Malerarbeiten laufen innerhalb einer Wohnung in einer festen Reihenfolge: zuerst Leitungen und Anschlüsse, dann Trockenbau und Wandaufbau, danach Böden und zuletzt die malermäßige Fertigstellung. Diese Reihenfolge verhindert, dass bereits fertige Gewerke durch nachfolgende Arbeiten wieder beschädigt oder verschmutzt werden. Einzelne Fachthemen wie Bad oder Wärmepumpe werden bei Bedarf gesondert abgestimmt, wenn sie über den reinen Wohnungsinnenausbau hinausgehen." },
      { titel: "Was ist bei einer bewohnten Wohnungssanierung zu beachten?", text: "Bleiben Bewohner während der Sanierung in der Wohnung, wird die Reihenfolge der Gewerke so geplant, dass mindestens ein nutzbarer Bereich erhalten bleibt, etwa durch raumweise Abschnitte statt Komplettöffnung aller Räume gleichzeitig. Staubschutz und Abdeckung angrenzender, nicht sanierter Bereiche gehören zur Grundausstattung jeder Innenausbau-Baustelle. Bei Eigentumswohnungen ist zusätzlich zu klären, ob Eingriffe in Leitungen oder Wände die Zustimmung der Eigentümergemeinschaft erfordern." },
    ],
    boxTitel: "Innenausbau nach Plan – ein Ansprechpartner, ein Zeitfenster",
    ausEinerHandText: "Wohnungssanierung ist bei Renodex der komplette Innenausbau einer einzelnen Wohnung – im Unterschied zur Haussanierung, die die Gebäudehülle von außen betrifft, und zur Komplettsanierung, die beides gemeinsam abdeckt.",
    faqFrage: "Kann eine Wohnung während der Sanierung bewohnt bleiben?",
    faqAntwort: "Das hängt vom Umfang der Arbeiten ab. Bei einzelnen Gewerken ist ein Verbleib oft möglich, bei einer Komplettsanierung empfiehlt sich meist ein vorübergehender Auszug. Renodex bespricht das im Vorfeld transparent.",
    weitereFragen: [
      { frage: "Kann eine Wohnungssanierung auch nur einzelne Räume umfassen?", antwort: "Ja, der Innenausbau muss sich nicht auf die gesamte Wohnung erstrecken. Häufig werden einzelne Räume oder Bereiche saniert, während der Rest der Wohnung unverändert bleibt und weiter genutzt wird. Die Gewerke-Reihenfolge (Elektro/Sanitär/Heizung vor Trockenbau, Trockenbau vor Boden und Malerarbeiten) gilt dann für den jeweiligen Teilbereich." },
      { frage: "Wird bei der Wohnungssanierung auch die alte Bausubstanz geprüft?", antwort: "Vor Beginn der eigentlichen Arbeiten wird der bestehende Zustand von Elektroleitungen, Wasserinstallation und Wandaufbau gesichtet, soweit er über eingereichte Fotos oder Videos erkennbar oder vor Ort zugänglich ist. Auffälligkeiten wie veraltete Elektroinstallation ohne FI-Schutzschalter oder erkennbare Feuchtestellen fließen in die Planung der Sanierungsreihenfolge ein." },
      { frage: "Wie werden Materialien für Böden und Malerarbeiten ausgewählt?", antwort: "Die Auswahl von Bodenbelägen, Wandfarben und Oberflächen erfolgt in Abstimmung mit der Nutzung des jeweiligen Raums und den baulichen Gegebenheiten, etwa Feuchtebelastung in Bädern oder Trittschallanforderungen bei Eigentumswohnungen. Konkrete Produktvorschläge werden erst nach Sichtung der Wohnung gemacht, nicht pauschal vorab festgelegt." },
    ],

  },
  {
    slug: "renovierung",
    title: "Renovierung",
    metaTitle: "Renovierung München – Wände, Böden, Türen | Renodex",
    metaDescription: "Wände vergilbt, Boden abgenutzt, Türen klemmen? Renodex koordiniert Anstrich, Böden und Türen zur Renovierung in München. Anfrage mit Fotos per E-Mail.",
    heroFrage: "Renovierung oder Sanierung in München – wo liegt der Unterschied?",
    heroLead: "Eine Renovierung erneuert Oberflächen und Ausstattung, ohne in die Bausubstanz einzugreifen – etwa Malerarbeiten, Böden oder Türen. Renodex übernimmt Renovierungen als eigenständiges Vorhaben oder als Teil einer größeren Sanierung.",
    heroImage: "/images/optimized/renovierung-waende-streichen.webp",
    heroImageAlt: "Maler streicht bei einer Renovierung die Wände, der Boden ist abgedeckt",
    problemUeberschrift: "Mehrere kleine Gewerke, ein überschaubares Budget",
    problemText: "Bei einer Renovierung sollen oft mehrere Räume gleichzeitig aufgefrischt werden – neue Farbe, neue Böden, vielleicht neue Türen. Für jedes Gewerk einen eigenen Handwerker zu finden, kostet Zeit, die bei einem überschaubaren Vorhaben oft in keinem Verhältnis zum Aufwand steht.",
    loesungUeberschrift: "Renovierung aus einer Hand, ohne Umwege",
    loesungPunkte: [
      "Malerarbeiten, Böden und Türen aus einer Beauftragung",
      "Ein Termin für die Besichtigung, ein Angebot für alle Arbeiten",
      "Auf Wunsch Kombination mit Elektro- oder Sanitärarbeiten",
      "Klare Absprache zu Umfang und Zeitrahmen",
    ],
    vertiefungUeberschrift: "Was zählt bei RENODEX zur Renovierung – und was nicht?",
    vertiefungAbschnitte: [
      { titel: "Wo endet die Renovierung, wo beginnt die Sanierung?", text: "Renovierung meint bei RENODEX ausschließlich Oberflächenarbeiten: Wände und Decken streichen oder tapezieren, Bodenbeläge verlegen oder austauschen, Türen erneuern oder anpassen. Sobald Leitungen, Wände, Estrich oder Dämmung betroffen sind, handelt es sich um eine Sanierung mit anderem Aufwand und anderer Gewerkeplanung. Diese Trennung entscheidet über Bauzeit, Kosten und ob eine Wohnung während der Arbeiten bewohnbar bleibt." },
      { titel: "Warum ist eine Renovierung deutlich schneller als eine Sanierung?", text: "Da bei der Renovierung keine Wände geöffnet, keine Leitungen verlegt und keine Bausubstanz verändert werden, entfallen Stemmarbeiten, Trocknungszeiten und die meisten Genehmigungsschritte. Anstrich, Bodenbelag und Türen lassen sich in aufeinanderfolgenden Arbeitsschritten planen, oft raumweise, sodass ein Teil der Wohnung nutzbar bleibt, während im anderen gearbeitet wird. Das unterscheidet den Aufwand klar von einer Bad- oder Komplettsanierung." },
      { titel: "Wie läuft die Abstimmung bei mehreren betroffenen Räumen ab?", text: "Farbe, Boden und Türen werden bei RENODEX als ein zusammenhängendes Paket geplant, damit Übergänge zwischen Räumen und Materialien stimmig wirken – etwa Sockelleisten, Bodenniveau an Türschwellen oder Anstrichfarbe im Verhältnis zum Bodenton. Sind zusätzlich Elektro-, Sanitär- oder Trockenbauarbeiten gewünscht, wird das als separates Gewerk mit dem zuständigen Team abgestimmt, nicht als Teil der Renovierungsleistung selbst." },
    ],
    boxTitel: "Renovierung ohne Substanzeingriff",
    ausEinerHandText: "Auch kleinere Renovierungen profitieren vom Prinzip aus einer Hand: Renodex bündelt die benötigten Gewerke, statt mehrere Einzelaufträge zu vergeben.",
    faqFrage: "Ab welchem Umfang lohnt sich eine Renovierung durch Renodex?",
    faqAntwort: "Renodex übernimmt sowohl einzelne Räume als auch mehrere Gewerke im Verbund. Ein kurzes Gespräch zum Vorhaben zeigt, ob sich eine gebündelte Beauftragung lohnt.",
    weitereFragen: [
      { frage: "Kann während einer Renovierung in der Wohnung gewohnt werden?", antwort: "In vielen Fällen ja, da keine Leitungen oder tragenden Bauteile betroffen sind. Die Arbeiten lassen sich raumweise oder in Etappen einteilen, sodass zumindest ein Teil der Wohnung nutzbar bleibt. Bei starker Geruchsbelastung durch Anstriche oder bei größerem Bodenaustausch über mehrere Räume kann eine kurzzeitige Ausweichlösung sinnvoller sein – das wird im Einzelfall besprochen." },
      { frage: "Welche Bodenbeläge kommen bei einer reinen Renovierung infrage?", antwort: "Je nach Untergrund und vorhandenem Aufbau eignen sich Laminat, Vinyl, Parkett oder Fliesen, sofern keine Anpassung des Estrichs nötig ist. Ist der vorhandene Unterboden uneben oder beschädigt, kann ein Ausgleich vor der Verlegung notwendig werden – das wird vor Beginn geprüft und ist Teil der Bodenverlegung als eigenständiges Gewerk, nicht der reinen Anstrich- oder Türenarbeit." },
      { frage: "Müssen alte Türen komplett ausgetauscht oder können sie angepasst werden?", antwort: "Beides ist möglich. Passt die Zarge noch, lässt sich oft nur das Türblatt tauschen, was Aufwand und Kosten reduziert. Ist die Zarge beschädigt, verzogen oder passt nicht mehr zum neuen Bodenaufbau, wird die komplette Einheit erneuert. Welche Variante infrage kommt, zeigt sich beim Aufmaß anhand von Zustand und Maßhaltigkeit der vorhandenen Tür." },
    ],

  },
  {
    slug: "badsanierung",
    title: "Badsanierung",
    metaTitle: "Badsanierung München – altes Bad erneuern | Renodex",
    metaDescription: "Fliesen alt, Fugen dunkel, Dusche zu eng? Renodex koordiniert Sanitär, Elektro und Fliesen für Ihr Bad in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Badsanierung in München: Was gehört zu einem neuen Bad dazu?",
    heroLead: "Die Fliesen stammen aus einer anderen Zeit, die Fugen werden dunkel, und die Wanne soll einer bodengleichen Dusche weichen. Im Bad arbeiten Sanitär, Elektro und Fliesenleger auf wenigen Quadratmetern. Eingetragene Fachfirmen führen die Arbeiten aus. Renodex koordiniert die Reihenfolge.",
    heroImage: "/images/optimized/badsanierung-armatur-montage-muenchen.webp",
    heroImageAlt: "Installateur montiert eine neue Armatur im entkernten Bad",
    problemUeberschrift: "Warum ist eine Badsanierung aufwendiger als gedacht?",
    problemText: "Im Bad liegen Wasserleitungen, Abfluss, Strom und Abdichtung dicht beieinander. Ein Fehler in einer Schicht zeigt sich oft erst später, etwa als Wasserfleck in der Wohnung darunter. Neue Fliesen auf alten Leitungen verdecken das Problem nur. Deshalb wird vor der Planung geklärt, was hinter den Fliesen liegt.",
    loesungUeberschrift: "Wie läuft eine Badsanierung mit Renodex ab?",
    loesungPunkte: [
      "Sie schicken Fotos, Maße und einen Grundriss Ihres Bads",
      "Eingetragene Fachfirmen prüfen Leitungen, Abfluss und Elektrik",
      "Planung von Dusche, Wanne und auf Wunsch barrierearmen Lösungen",
      "Renodex stimmt Sanitär, Elektro, Abdichtung und Fliesen aufeinander ab",
    ],
    vertiefungUeberschrift: "Worauf kommt es bei einer Badsanierung an?",
    vertiefungAbschnitte: [
      { titel: "Wie wird ein Bad richtig abgedichtet?", text: "Im Dusch- und Wannenbereich liegt unter den Fliesen eine Verbundabdichtung. Sie wird nach der DIN-Norm für Innenraumabdichtungen ausgeführt, bevor der Fliesenleger beginnt. Bodengleiche Duschen brauchen zusätzlich ein Gefälle zum Ablauf. Die Abdichtungsebene wird vor dem Verfliesen fotografiert. So bleibt nachvollziehbar, was hinter den Fliesen liegt." },
      { titel: "Was gilt für Steckdosen und Licht im Bad?", text: "Die VDE-Normen teilen das Bad in Schutzbereiche rund um Wanne und Dusche ein. Je näher ein Gerät am Wasser liegt, desto strenger sind die Vorgaben für Schutzart und Abstand. Bei einer Sanierung prüft die Elektro-Fachfirma die vorhandene Installation gegen diese Bereiche. Steckdosen und Leuchten werden bei Bedarf versetzt." },
      { titel: "Lässt sich eine bodengleiche Dusche nachrüsten?", text: "In vielen Bädern ja. Entscheidend ist die Aufbauhöhe zwischen Rohdecke und fertigem Boden. Der Ablauf braucht Gefälle zur Abwasserleitung, sonst steht Wasser in der Dusche. Reicht die Höhe nicht, kommen flache Bodenabläufe oder ein abgesenkter Estrich infrage. Das prüft die Fachfirma anhand Ihrer Maße und Fotos." },
    ],
    boxTitel: "Sanitär, Elektro und Fliesen in einem Bauablauf",
    ausEinerHandText: "Eine Badsanierung ist oft Teil einer größeren Wohnungs- oder Komplettsanierung. Renodex plant sie dann im Bauablauf der übrigen Gewerke mit.",
    faqFrage: "Was kostet eine Badsanierung in München?",
    faqAntwort: "Die Preisübersicht von Renodex nennt für eine komplette Badsanierung eine typische Spanne von 800 bis 1.800 Euro je Quadratmeter. Wo Ihr Bad liegt, hängt von Ausstattung, Leitungsarbeiten und Änderungen am Grundriss ab. Verbindlich ist erst das Festpreisangebot, das Renodex nach der Besichtigung erstellt.",
    weitereFragen: [
      { frage: "Muss die Sanitärinstallation immer mit erneuert werden?", antwort: "Nicht immer. Das hängt von Alter und Material der Leitungen ab. Sind die Wände ohnehin offen, lohnt der Blick auf alte, verzinkte Rohre besonders. Ob der Bestand bleiben kann, beurteilt die Sanitär-Fachfirma." },
      { frage: "Wird beim Rückbau auf Asbest geachtet?", antwort: "Ja. In Bädern aus Gebäuden vor 1993 können Fliesenkleber oder Spachtelmassen Asbest enthalten. Bei Verdacht klärt eine Materialprobe den Befund. Bestätigt er sich, wird die Asbestsanierung vor dem weiteren Rückbau eingeplant." },
      { frage: "Wie wird ein Bad ohne Fenster entlüftet?", antwort: "Ein fensterloses Bad braucht eine mechanische Lüftung, meist einen Ventilator mit Nachlauf. Er führt die Feuchtigkeit nach dem Duschen ab. Ob eine vorhandene Lüftungsleitung genutzt werden kann, zeigen Grundriss und Fotos." },
      { frage: "Lässt sich das Bad barrierearm umbauen?", antwort: "Meist ja, im Zuge der Sanierung. Dazu gehören eine bodengleiche Dusche, rutschhemmende Fliesen und genug Bewegungsfläche. Ob der Grundriss das hergibt, prüft die Fachfirma anhand Ihrer Maße. Ob es dafür aktuell Zuschüsse gibt, zeigt der Stand bei der KfW." },
      { frage: "Wer führt die Arbeiten im Bad aus?", antwort: "Eingetragene Fachfirmen für Sanitär, Elektro und Fliesen. Den Vertrag über die Bauleistung schließen Sie wahlweise mit Renodex, auch als Gesamtpaket zu einem Festpreis, oder direkt mit der ausführenden Fachfirma. Renodex koordiniert in beiden Fällen Termine und Reihenfolge der Gewerke." },
    ],
    verwandteThemen: [
      { href: "/leistungen/sanitaer", text: "Sanitär" },
      { href: "/leistungen/komplettsanierung", text: "Komplettsanierung" },
      { href: "/leistungen/bodenverlegung", text: "Bodenverlegung" },
    ],
  },
  {
    slug: "bodenverlegung",
    title: "Bodenverlegung",
    metaTitle: "Bodenverlegung München – Parkett, Vinyl, Fliesen | Renodex",
    metaDescription: "Neuer Boden, aber welcher passt auf Ihren Estrich? Renodex koordiniert Fachfirmen für Bodenverlegung in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Bodenverlegung in München: Worauf kommt es an?",
    heroLead: "Ein neuer Boden ist mehr als nur die sichtbare Oberfläche – der Unterbau entscheidet über Langlebigkeit und Wohnqualität. Renodex verlegt Böden fachgerecht, abgestimmt auf Raum, Nutzung und vorhandenen Unterbau.",
    heroImage: "/images/optimized/parkett-fischgraet-verlegen.webp",
    heroImageAlt: "Bodenleger verlegt Eichenparkett im Fischgrätmuster auf Estrich",
    problemUeberschrift: "Unebener Unterbau, falsche Feuchtigkeitswerte, sichtbare Mängel später",
    problemText: "Wird ein Boden ohne fachgerechte Vorbereitung des Unterbaus verlegt, zeigen sich Mängel oft erst Monate später – Fugen öffnen sich, der Boden arbeitet, oder es bildet sich Feuchtigkeit unter dem Belag.",
    loesungUeberschrift: "Verlegung mit geprüftem Unterbau",
    loesungPunkte: [
      "Prüfung von Estrich und Feuchtigkeit vor der Verlegung",
      "Fachgerechte Verlegung nach Herstellervorgaben",
      "Abstimmung mit Heizungs- und Elektroarbeiten im selben Raum",
      "Beratung zur passenden Bodenart je nach Nutzung",
    ],
    vertiefungUeberschrift: "Wie läuft eine professionelle Bodenverlegung ab und worauf kommt es beim Unterbau an?",
    vertiefungAbschnitte: [
      { titel: "Welche Rolle spielt die Estrich-Prüfung vor der Verlegung?", text: "Vor jeder Belagsverlegung wird die Restfeuchte im Estrich mit der CM-Messung (Calciumcarbid-Methode) geprüft. Nur so lässt sich belegen, ob der Untergrund tatsächlich belegreif ist – ein zu feuchter Estrich führt bei Parkett und Laminat zu Quellungen, bei Vinyl zu Blasenbildung und Ablösungen. Die Grenzwerte unterscheiden sich je nach Estrichart (Zementestrich, Anhydritestrich) und geplantem Bodenbelag, weshalb die Messung immer belagsspezifisch erfolgt und dokumentiert wird." },
      { titel: "Welche Vorarbeiten sind vor der eigentlichen Verlegung nötig?", text: "Vor der Verlegung wird der Untergrund auf Ebenheit, Tragfähigkeit und Risse geprüft. Unebenheiten werden mit Spachtelmasse ausgeglichen, lose oder schadhafte Altbeläge entfernt. Bei Bedarf kommt eine Dampfsperre oder Trittschalldämmung zum Einsatz, abgestimmt auf Belagsart und Nutzung des Raums. Erst nach abgeschlossener Untergrundvorbereitung folgt die eigentliche Verlegung – dieser Schritt entscheidet maßgeblich über die spätere Haltbarkeit des Bodens." },
      { titel: "Welche Bodenbeläge werden verlegt und wie unterscheiden sie sich in der Verarbeitung?", text: "Parkett wird schwimmend verlegt oder vollflächig verklebt, je nach Holzart und Raumgröße unter Beachtung der Dehnungsfugen an Wänden und Übergängen. Vinylböden werden meist schwimmend geklickt oder vollflächig verklebt und eignen sich wegen ihrer Feuchtigkeitsbeständigkeit auch für Küchen und Bäder. Fliesen erfordern einen tragfähigen, ebenen Untergrund sowie eine fachgerechte Verlegung im Dünn- oder Mittelbettverfahren inklusive Verfugung. Laminat wird schwimmend auf einer Trittschalldämmung verlegt und ist eine wirtschaftliche Lösung für kurzfristig nutzbare Räume." },
    ],
    boxTitel: "Böden aus einer Hand: Aufmaß, Unterbau, Verlegung",
    ausEinerHandText: "Bodenverlegung wird bei Renodex meist gemeinsam mit Sanitär-, Heizungs- oder Malerarbeiten im selben Bauabschnitt koordiniert.",
    faqFrage: "Welche Bodenarten verlegt Renodex?",
    faqAntwort: "Renodex berät zur passenden Bodenart abhängig von Raum, Nutzung und Budget und übernimmt die fachgerechte Verlegung als Teil der Sanierung.",
    weitereFragen: [
      { frage: "Kann ein neuer Bodenbelag auf den alten Boden verlegt werden?", antwort: "Das hängt vom Zustand des Altbelags und der gewünschten Aufbauhöhe ab. Ein tragfähiger, ebener Altbelag kann bei manchen Belagsarten (z.B. Vinyl auf Fliesen) als Untergrund dienen, sofern die Fugen unproblematisch sind. Bei Parkett oder größeren Unebenheiten ist meist ein Rückbau bis auf den Estrich sinnvoller, damit die Feuchtigkeitswerte korrekt geprüft und ein sauberer Unterbau hergestellt werden kann." },
      { frage: "Wie wird der Boden an Türübergängen und Anschlüssen fachgerecht gelöst?", antwort: "An Türübergängen zwischen unterschiedlichen Belägen oder Räumen kommen Übergangsprofile zum Einsatz, die Höhenunterschiede ausgleichen und die Dehnungsfuge des schwimmenden Bodens kaschieren. An Wandanschlüssen sorgt eine Randfuge dafür, dass sich der Boden bei Temperatur- und Feuchteschwankungen ausdehnen kann, ohne sich zu wölben. Sockelleisten schließen die Fuge anschließend optisch ab." },
      { frage: "Warum ist eine schwimmende Verlegung nicht immer die richtige Wahl?", antwort: "Schwimmende Verlegung ist schnell und kostengünstig, hat aber Grenzen: In stark beanspruchten oder sehr großen Räumen kann sich der Belag durch fehlende Fixierung stärker bewegen. Bei Fußbodenheizung ist eine vollflächige Verklebung oft die bessere Wärmeleitung, und bei Feuchträumen mit Abdichtungspflicht ist eine verklebte Lösung meist die sicherere Variante. Die Entscheidung wird immer anhand von Raumnutzung, Untergrund und Belagsart getroffen." },
    ],

  },
  {
    slug: "malerarbeiten-fassade",
    title: "Malerarbeiten und Fassade",
    metaTitle: "Malerarbeiten & Fassadenanstrich München | Renodex",
    metaDescription: "Fassade kreidet, Putz reißt, Wände brauchen neue Farbe? Renodex koordiniert Malerarbeiten innen und außen in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Malerarbeiten und Fassade in München: Was ist zu beachten?",
    heroLead: "Ob Innenräume oder Fassade – ein sauberes Ergebnis hängt an der Vorbereitung des Untergrunds mindestens so sehr wie am Anstrich selbst. Renodex übernimmt Malerarbeiten innen und außen als eigenständiges Vorhaben oder im Rahmen einer Sanierung.",
    heroImage: "/images/optimized/fassade-streichen-maler-geruest.webp",
    heroImageAlt: "Maler streicht eine Hausfassade, im Hintergrund steht das Gerüst",
    problemUeberschrift: "Untergrund, Witterung und Termine passen selten von allein zusammen",
    problemText: "Innenanstriche müssen sich in den Bauablauf anderer Gewerke einfügen, Fassadenarbeiten hängen zusätzlich vom Wetter ab. Ohne Abstimmung verzögert sich am Ende der gesamte Zeitplan der Sanierung.",
    loesungUeberschrift: "Malerarbeiten im Bauablauf mitgeplant",
    loesungPunkte: [
      "Untergrundvorbereitung nach Zustand der Wände",
      "Terminierung im Zusammenspiel mit anderen Gewerken",
      "Fassadenanstrich mit Blick auf Witterung und Dämmung",
      "Farbberatung auf Wunsch",
    ],
    vertiefungUeberschrift: "Wie oft muss eine Fassade neu gestrichen werden?",
    vertiefungAbschnitte: [
      { titel: "Wie oft muss eine Fassade neu gestrichen werden?", text: "Ein mineralischer oder Silikatanstrich hält je nach Witterungslage, Ausrichtung und Vorschaden zwischen zehn und fünfzehn Jahren, bevor die Deckkraft nachlässt und Risse im Putz sichtbar werden. Wetterseiten (West/Südwest) altern durch Schlagregen schneller als geschützte Fassadenteile. Vor jedem Neuanstrich wird der Untergrund geprüft: kreidende, abblätternde oder von Algen befallene Flächen brauchen eine Grundreinigung und ggf. einen Fungizid-Grundanstrich, sonst hält die neue Farbschicht nicht." },
      { titel: "Welche Farbe passt zu welchem Untergrund?", text: "Silikatfarbe verbindet sich mineralisch mit mineralischem Putz und ist diffusionsoffen – Standard bei Altbau-Fassaden mit Kalk- oder Zementputz. Silikonharzfarbe ist wasserabweisender und flexibler, geeignet für WDVS-Fassaden und Untergründe mit feinen Rissen. Dispersionsfarbe ist günstiger, aber weniger diffusionsoffen und für Feuchtprobleme ungeeignet. Die Farbwahl richtet sich nach dem vorhandenen Putzsystem, nicht nach Optik allein." },
      { titel: "Was gehört zur Vorbereitung vor dem Streichen?", text: "Vor jedem Außenanstrich stehen Hochdruckreinigung des Untergrunds, Ausbesserung von Rissen und Abplatzungen im Putz sowie das Abkleben von Fenstern und Rollladenkästen. Innen betrifft die Vorbereitung Spachtelarbeiten an Wandunebenheiten, Grundierung bei saugenden Untergründen und Abdecken von Böden und Einrichtung. Erst nach vollständiger Trocknung der Vorarbeiten wird der eigentliche Anstrich aufgetragen." },
    ],
    boxTitel: "Fassade und Anstrich: Material nach Untergrund",
    ausEinerHandText: "Malerarbeiten sind oft der letzte Schritt einer Sanierung – Renodex terminiert sie so, dass sie nahtlos an die vorherigen Gewerke anschließen.",
    faqFrage: "Übernimmt Renodex auch reine Fassadenarbeiten ohne Innensanierung?",
    faqAntwort: "Ja, Fassadenanstrich und Malerarbeiten sind auch als eigenständiger Auftrag möglich, unabhängig von einer größeren Sanierung.",
    weitereFragen: [
      { frage: "Kann bei laufendem Betrieb oder bewohntem Haus gestrichen werden?", antwort: "Innenanstriche werden raumweise abgestimmt, sodass Küche und Bad nutzbar bleiben, während andere Zimmer bearbeitet werden. Außenfassaden sind während der Trocknungszeit witterungsabhängig, der Zugang zu Haus und Grundstück bleibt dabei bestehen." },
      { frage: "Was kostet ein Fassadenanstrich?", antwort: "Der Preis hängt von Fassadenfläche, Gerüstbedarf, Zustand des Untergrunds (Reparaturaufwand) und gewähltem Farbsystem ab. Eine verlässliche Zahl setzt eine Begutachtung der Fassade voraus – über den digitalen Erstkontakt mit Fotos ist eine erste Einschätzung ohne Vor-Ort-Termin möglich." },
      { frage: "Wird bei einer Fassadensanierung auch die Dämmung mitgemacht?", antwort: "Ein reiner Anstrich dämmt nicht zusätzlich. Soll die Fassade zugleich energetisch ertuechtigt werden, wird das als eigener Schritt (WDVS) mit dem Anstrich abgestimmt und geplant." },
    ],

  },
  {
    slug: "mauerwerksabdichtung",
    title: "Mauerwerksabdichtung",
    metaTitle: "Mauerwerksabdichtung München – feuchter Keller | Renodex",
    metaDescription: "Salzränder, abplatzender Putz, muffiger Keller? Renodex koordiniert Fachfirmen für Mauerwerksabdichtung in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Feuchtes Mauerwerk in München: Woran erkennt man es?",
    heroLead: "Feuchtigkeit im Mauerwerk zeigt sich häufig durch Salzausblühungen, abplatzenden Putz oder muffigen Geruch im Keller. Renodex prüft die Ursache und führt eine fachgerechte Abdichtung durch.",
    heroImage: "/images/optimized/mauerwerk-abdichten-feuchte-ziegelwand.webp",
    heroImageAlt: "Handwerker trägt Abdichtung auf feuchtes Ziegelmauerwerk auf",
    problemUeberschrift: "Feuchtigkeit im Mauerwerk bleibt lange unbemerkt",
    problemText: "Aufsteigende oder seitlich eindringende Feuchtigkeit schädigt das Mauerwerk oft über Jahre, bevor sichtbare Schäden entstehen. Wird die Ursache nicht behoben, wirkt jede oberflächliche Reparatur nur kurzfristig.",
    loesungUeberschrift: "Ursachenanalyse vor der Abdichtung",
    loesungPunkte: [
      "Prüfung der Feuchtigkeitsursache vor Beginn der Arbeiten",
      "Fachgerechte Horizontal- und Vertikalabdichtung",
      "Abstimmung mit Kellersanierung, falls betroffen",
      "Langfristige Lösung statt oberflächlicher Reparatur",
    ],
    vertiefungUeberschrift: "Wie erkennt man aufsteigende Feuchtigkeit im Mauerwerk?",
    vertiefungAbschnitte: [
      { titel: "Welche Anzeichen deuten auf feuchtes Mauerwerk hin?", text: "Typische Warnzeichen sind abblätternder Putz, Salzausblühungen (weiße Kristallschichten) im Sockelbereich, muffiger Geruch in Keller- oder Erdgeschossräumen sowie dunkle Verfärbungen an der Wandunterseite. Diese Symptome treten meist dort auf, wo die Horizontalsperre fehlt, beschädigt oder durch nachträgliche bauliche Eingriffe unterbrochen wurde. Eine Feuchtemessung mit Datenerfassung an mehreren Wandpunkten zeigt, ob es sich um aufsteigende Feuchte, seitlich eindringendes Wasser oder Kondensation handelt – die Ursache entscheidet über das passende Abdichtungsverfahren." },
      { titel: "Horizontalsperre oder Vertikalabdichtung – was wird wann eingesetzt?", text: "Die Horizontalsperre unterbindet den kapillaren Feuchtetransport von unten nach oben im Mauerwerk, etwa durch Injektionsverfahren mit Spezialharzen oder mechanisches Einbringen einer Sperrschicht. Die Vertikalabdichtung schützt erdberührte Kelleraußenwände vor seitlich drückendem oder nicht drückendem Wasser und wird von außen als Bitumen-, Dickbeschichtungs- oder Folienabdichtung aufgebracht. Bei Bestandsgebäuden kommen häufig beide Verfahren kombiniert zum Einsatz, weil aufsteigende und seitliche Feuchte oft gleichzeitig auftreten." },
      { titel: "Was passiert bei einer Injektionsabdichtung im Detail?", text: "Bei der Injektionsabdichtung werden in einer definierten Bohrlochreihe entlang der Wand Spezialharze oder Cremes eingebracht, die im Mauerwerk aushärten und eine wasserabweisende Sperrschicht bilden. Das Verfahren funktioniert bei den meisten Mauerwerksarten (Ziegel, Naturstein, Mischmauerwerk) und kommt ohne größere Aufgrabung aus, wenn nur die aufsteigende Feuchte betroffen ist. Bei zusätzlich vorhandener seitlicher Durchfeuchtung ist ergänzend eine Freilegung der Kelleraußenwand für die Vertikalabdichtung notwendig." },
    ],
    boxTitel: "Feuchteschutz mit System",
    ausEinerHandText: "Mauerwerksabdichtung ist oft der erste Schritt vor einer Kellersanierung oder Innenraumrenovierung – Renodex plant sie entsprechend in die Gesamtsanierung ein.",
    faqFrage: "Wie erkennt man, ob eine Mauerwerksabdichtung nötig ist?",
    faqAntwort: "Typische Anzeichen sind Feuchtigkeitsflecken, abblätternder Putz oder Salzausblühungen an Kellerwänden. Eine Besichtigung vor Ort klärt die genaue Ursache.",
    weitereFragen: [
      { frage: "Kann Mauerwerksabdichtung von innen erfolgen, wenn die Außenwand nicht freigelegt werden kann?", antwort: "Ja, bei angrenzender Bebauung oder befestigten Flächen wird häufig eine Innenabdichtung mit mineralischen Dichtschlämmen oder Sanierputz eingesetzt. Sie verhindert das Eindringen der Feuchtigkeit in den Innenraum, beseitigt aber nicht die Ursache in der Wand selbst – deshalb wird sie meist mit einer Horizontalsperre kombiniert." },
      { frage: "Wie lange hält eine fachgerecht ausgeführte Horizontalsperre?", antwort: "Bei korrekter Ausführung und passendem Injektionsmittel für die jeweilige Mauerwerksart ist die Sperrschicht dauerhaft wirksam und muss im Regelfall nicht erneuert werden. Voraussetzung ist eine vorherige Bauteilöffnung bzw. Materialanalyse, damit das Harz auf den tatsächlichen Feuchtegehalt und die Porenstruktur des Mauerwerks abgestimmt wird." },
      { frage: "Muss bei einer Vertikalabdichtung auch die Drainage erneuert werden?", antwort: "Das hängt vom Zustand der vorhandenen Dränung ab und wird bei der Freilegung der Kelleraußenwand mitgeprüft. Eine funktionierende Ringdrainage entlastet die neue Abdichtungsschicht, indem sie drückendes Wasser vom Fundament ableitet – ob sie erneuert werden muss, zeigt sich erst nach Öffnung der Baugrube." },
    ],

  },
  {
    slug: "asbestsanierung",
    title: "Asbestsanierung",
    metaTitle: "Asbestsanierung München – Verdacht klären | Renodex",
    metaDescription: "Altbau vor 1993 und Verdacht auf Asbest? Renodex koordiniert Fachfirmen für Probe, Entfernung und Entsorgung in München. Anfrage mit Fotos per E-Mail.",
    heroFrage: "Asbestsanierung in München: Wann ist sie notwendig?",
    heroLead: "In Gebäuden aus der Bauzeit vor 1993 können asbesthaltige Materialien verbaut sein, etwa in Bodenbelägen, Dachplatten oder Rohrisolierungen. Renodex führt die Entfernung fachgerecht und nach den geltenden Vorschriften durch.",
    heroImage: "/images/optimized/asbestsanierung-schutzanzug-atemschutz.webp",
    heroImageAlt: "Fachkraft in Schutzanzug und Atemschutz baut belastete Bauteile zurück",
    problemUeberschrift: "Ungeprüfte Sanierung bei Verdacht auf Asbest ist ein Risiko",
    problemText: "Wird bei Sanierungsarbeiten in älteren Gebäuden asbesthaltiges Material unsachgemäß entfernt oder beschädigt, können Fasern freigesetzt werden. Das betrifft nicht nur die Baustelle selbst, sondern auch angrenzende Bereiche.",
    loesungUeberschrift: "Fachgerechte Entfernung nach Vorschrift",
    loesungPunkte: [
      "Prüfung auf asbesthaltige Materialien vor Sanierungsbeginn",
      "Fachgerechte, vorschriftsgemäße Entfernung",
      "Sichere Entsorgung nach geltenden Bestimmungen",
      "Einbindung in den Gesamtablauf der Sanierung",
    ],
    vertiefungUeberschrift: "Wie läuft eine Asbestsanierung fachgerecht ab?",
    vertiefungAbschnitte: [
      { titel: "Welche Materialien sind im Altbau oft asbesthaltig?", text: "In Gebäuden vor dem Baujahr 1993 finden sich asbesthaltige Baustoffe häufig in Fassadenplatten, Bodenbelägen (Vinyl-Fliesen samt Kleber), Dachplatten aus Well-Eternit, Rohrisolierungen und Spachtelmassen unter Fliesen. Ein Verdacht lässt sich nicht durch bloße Optik klären - erst eine Materialprobe im akkreditierten Labor gibt Gewissheit, ob und in welcher Bindungsform (fest oder schwach gebunden) Asbest vorliegt." },
      { titel: "Was schreibt die TRGS 519 für die Ausführung vor?", text: "Die Technische Regel für Gefahrstoffe 519 regelt Abbruch-, Sanierungs- und Instandhaltungsarbeiten mit Asbest verbindlich. Je nach Bindungsform sind Schwarz-Weiß-Bereiche mit Personenschleuse, Unterdruckhaltung und H-Klasse-Absaugung, staubdichte Verpackung des Abbruchmaterials sowie eine Freimessung durch unabhängige Messstellen vor Freigabe des Bereichs vorgeschrieben. Vor Beginn ist eine Anzeige bei der zuständigen Behörde (Gewerbeaufsicht) einzureichen." },
      { titel: "Wie wird belastetes Material entsorgt?", text: "Asbesthaltige Abfälle gelten als gefährlicher Abfall und dürfen nur luftdicht verpackt (Folie, gekennzeichnete Big Bags) über zugelassene Entsorgungsbetriebe auf dafür vorgesehenen Deponien abgegeben werden. Für den Transport gilt Nachweispflicht - der Entsorgungsweg wird dokumentiert und der Auftraggeber erhält die entsprechenden Belege zur Vorlage bei Behörden oder Versicherung." },
    ],
    boxTitel: "Sicher entfernt nach TRGS 519",
    ausEinerHandText: "Eine Asbestsanierung geht bei älteren Gebäuden häufig einer größeren Sanierung voraus – Renodex koordiniert sie im Vorfeld der weiteren Gewerke.",
    faqFrage: "Woran erkennt man, ob Asbest verbaut ist?",
    faqAntwort: "Eine sichere Einschätzung ist ohne fachliche Prüfung meist nicht möglich, insbesondere bei Gebäuden aus der Bauzeit vor 1993. Renodex berät zum weiteren Vorgehen.",
    weitereFragen: [
      { frage: "Muss eine Asbestsanierung immer behördlich angezeigt werden?", antwort: "Ja, Arbeiten mit Asbest sind vor Beginn bei der zuständigen Gewerbeaufsicht anzuzeigen - unabhängig von der Menge des betroffenen Materials. Die Anzeige umfasst Art und Umfang der Arbeiten sowie die vorgesehenen Schutzmaßnahmen." },
      { frage: "Kann ich asbesthaltige Platten selbst entfernen?", antwort: "Bei schwach gebundenem Asbest (z. B. Spritzasbest, manche Isolierungen) ist die Entfernung fachbetriebspflichtig und darf nicht in Eigenregie erfolgen. Bei fest gebundenem Material (z. B. Well-Eternit-Platten) gelten reduzierte, aber weiterhin verbindliche Schutzauflagen nach TRGS 519 - eine fachgerechte Einschätzung vor Beginn ist in jedem Fall sinnvoll." },
      { frage: "Wie erkenne ich, ob Sanierungsbedarf wirklich besteht?", antwort: "Sichtbare Beschädigung, Rissbildung oder Bohr-/Sägearbeiten an verdächtigen Bauteilen erhöhen die Faserfreisetzung und damit den Handlungsbedarf. Eine Materialprobe mit Laboranalyse schafft Klarheit, bevor überhaupt eine Sanierung geplant wird - so lässt sich unnötiger Aufwand vermeiden, wenn kein Asbest vorliegt." },
    ],

  },
  {
    slug: "tueren",
    title: "Türen",
    metaTitle: "Türen austauschen München – Tür & Zarge | Renodex",
    metaDescription: "Tür klemmt, Zarge verzogen, Schallschutz fehlt? Renodex koordiniert den Austausch von Innen- und Haustüren in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Türen in München: Wann lohnt sich der Austausch?",
    heroLead: "Alte Türen beeinträchtigen oft Dämmung, Schallschutz und Optik gleichermaßen. Renodex tauscht Innen- und Haustüren fachgerecht aus, passend zum jeweiligen Sanierungsvorhaben.",
    heroImage: "/images/optimized/tuer-einbauen-zarge-ausrichten.webp",
    heroImageAlt: "Monteur richtet eine Türzarge mit Wasserwaage aus",
    problemUeberschrift: "Alte Türen schließen schlecht, isolieren kaum",
    problemText: "Verzogene Zargen, undichte Dichtungen oder veraltete Beschläge sorgen dafür, dass Türen weder gut schließen noch ausreichend dämmen – ein Detail, das bei einer Sanierung leicht übersehen wird.",
    loesungUeberschrift: "Türeinbau abgestimmt auf die Sanierung",
    loesungPunkte: [
      "Fachgerechter Einbau von Innen- und Haustüren",
      "Abstimmung mit Boden- und Malerarbeiten",
      "Beratung zu Schall- und Wärmedämmung",
      "Passgenauer Einbau bei unregelmäßigen Bestandsmaßen",
    ],
    vertiefungUeberschrift: "Was kostet ein Türaustausch inklusive Zarge?",
    vertiefungAbschnitte: [
      { titel: "Was kostet ein Türaustausch inklusive Zarge?", text: "Der Preis für Innentür samt Zarge hängt von Wandaufbau, Türgröße und Ausführung (Zimmertür, Schallschutztür, Wohnungseingangstür) ab. Bei tragenden Wänden oder abweichendem Mauerwerk ist meist eine Anpassung der Zarge vor Ort nötig, was den Aufwand gegenüber einem reinen Blattwechsel erhöht. Eine verbindliche Kalkulation setzt Maße der vorhandenen Öffnung, Wandstärke und Fotos der aktuellen Situation voraus." },
      { titel: "Wie lange dauert der Austausch einer Zimmertür?", text: "Der reine Austausch von Türblatt und Zarge bei einer Standardöffnung ist in der Regel an einem Tag erledigt, sofern Maße passen und keine Anpassung des Mauerwerks nötig ist. Weicht die neue Zarge von der Wandstärke ab oder muss der Sturz nachgearbeitet werden, verlängert sich die Arbeit entsprechend. Putz- und Malerarbeiten rund um die neue Zarge werden mit dem jeweiligen Gewerk abgestimmt und separat terminiert." },
      { titel: "Welche Rolle spielt der Schallschutz bei Innentüren?", text: "Schallschutztüren unterscheiden sich von Standardtüren durch umlaufende Dichtungen, eine schwerere Türblattkonstruktion und eine passgenaue Zarge ohne Spalt zum Baukörper. Die erreichbare Schalldämmung hängt neben der Tür selbst auch vom Wandaufbau und der Ausführung des Bodenanschlusses ab. Bei Altbauten mit unebenen Laibungen ist häufig ein Anpassen der Zarge erforderlich, damit die Dichtungen vollflächig aufliegen." },
    ],
    boxTitel: "Türen und Zargen aus einer Hand",
    ausEinerHandText: "Der Türaustausch wird bei Renodex meist gemeinsam mit Boden- oder Malerarbeiten im selben Bauabschnitt eingeplant.",
    faqFrage: "Tauscht Renodex auch einzelne Türen ohne Gesamtsanierung aus?",
    faqAntwort: "Ja, der Austausch einzelner Türen ist auch unabhängig von einer größeren Sanierung möglich.",
    weitereFragen: [
      { frage: "Können Türen ausgetauscht werden, ohne die Wand neu zu verputzen?", antwort: "Bei einer passgenauen neuen Zarge im vorhandenen Maß bleibt die umliegende Wand meist unberührt. Weicht die neue Zarge im Format ab oder ist der Altputz an der Laibung beschädigt, wird das mit dem Maler-/Putzgewerk abgestimmt und die betroffene Fläche nachgearbeitet." },
      { frage: "Was ist der Unterschied zwischen Umfassungszarge und Blockzarge?", antwort: "Die Umfassungszarge umschließt die Wand von beiden Seiten und ist die gängige Lösung im Wohnbau bei Wandstärken bis etwa 24 cm. Die Blockzarge sitzt nur auf einer Wandseite auf und kommt bei stärkeren Wänden oder besonderen Anschlusssituationen zum Einsatz. Welche Variante passt, ergibt sich aus Wandstärke und vorhandenem Laibungsaufbau." },
      { frage: "Werden auch Wohnungseingangstüren mit Einbruchschutz ausgetauscht?", antwort: "Ja, neben Zimmertüren gehören auch Wohnungseingangstüren mit einbruchhemmender Ausstattung (Mehrfachverriegelung, verstärkte Zarge) zum Leistungsbild. Die passende Widerstandsklasse richtet sich nach der bestehenden Bausituation und wird anhand der eingereichten Fotos und Maße eingeschätzt." },
    ],

  },
  {
    slug: "elektroinstallation",
    title: "Elektroinstallation",
    metaTitle: "Elektroinstallation München – Elektrik erneuern | Renodex",
    metaDescription: "Sicherung fliegt raus, kein FI-Schalter? Renodex koordiniert Elektro-Fachfirmen in München. Fotos vom Sicherungskasten hochladen, Antwort per E-Mail.",
    heroFrage: "Elektroinstallation in München: Wann muss die alte Elektrik raus?",
    heroLead: "Die Sicherung fliegt, sobald Wasserkocher und Waschmaschine gleichzeitig laufen. Im Altbau fehlen Steckdosen, und im Kasten sitzen noch Schraubsicherungen. Eine eingetragene Elektro-Fachfirma prüft und erneuert die Installation. Renodex koordiniert Elektro mit Trockenbau, Bad und Heizung.",
    heroImage: "/images/optimized/elektroinstallation-sicherungskasten-altbau.webp",
    heroImageAlt: "Elektriker verdrahtet einen neuen Sicherungskasten in einer Altbauwohnung",
    problemUeberschrift: "Woran erkennt man eine veraltete Elektroinstallation?",
    problemText: "Alte Elektrik fällt meist im Alltag auf. Sicherungen lösen oft aus, Steckdosen werden warm, und in jedem Zimmer liegt ein Mehrfachstecker. Im Sicherungskasten fehlt häufig der Fehlerstromschutzschalter. Leitungen ohne Schutzleiter sieht man von außen nicht. Sie bleiben ein Risiko, bis eine Fachkraft die Anlage prüft.",
    loesungUeberschrift: "Wie läuft eine Elektroerneuerung mit Renodex ab?",
    loesungPunkte: [
      "Sie schicken Fotos von Sicherungskasten, Zählerschrank und Steckdosen",
      "Eine eingetragene Elektro-Fachfirma beurteilt den Zustand der Anlage",
      "Planung von Stromkreisen, Steckdosen und Anschlüssen nach Nutzung",
      "Renodex stimmt Elektro, Trockenbau und Malerarbeiten aufeinander ab",
    ],
    vertiefungUeberschrift: "Wann muss eine Elektroinstallation erneuert werden?",
    vertiefungAbschnitte: [
      { titel: "Was fehlt alten Sicherungskästen?", text: "Ältere Verteilungen arbeiten oft noch mit Schraubsicherungen und ohne Fehlerstromschutzschalter. Der FI-Schalter trennt den Stromkreis, wenn Strom über einen Menschen oder einen Defekt abfließt. Die geltenden VDE-Normen verlangen ihn unter anderem für Steckdosen- und Badstromkreise. Wird die Installation wesentlich geändert, kommt die Verteilung deshalb meist mit auf den Prüfstand." },
      { titel: "Welche Leitungen gelten als veraltet?", text: "In Altbauten liegen teils noch zweiadrige Leitungen ohne Schutzleiter oder Aluminiumleitungen. Sie sind für heutige Lasten und Schutzkonzepte nicht ausgelegt. Bei einer Sanierung ersetzt die Fachfirma sie durch Leitungen mit Schutzleiter. Die Verlegewege werden dokumentiert, bevor Putz oder Fliesen sie verdecken. So bleibt später nachvollziehbar, wo Leitungen liegen." },
      { titel: "Was braucht die Elektrik für Wärmepumpe, Wallbox und Photovoltaik?", text: "Wärmepumpe, Wallbox und Photovoltaikanlage belasten den Hausanschluss zusätzlich. Oft reicht der vorhandene Zählerschrank dafür nicht aus und muss erweitert oder erneuert werden. Solche Anlagen sind beim Netzbetreiber anzumelden. Die Elektro-Fachfirma plant Stromkreise und Zählerplatz deshalb gleich für die Geräte, die später dazukommen sollen." },
    ],
    boxTitel: "Elektrik im Takt mit den übrigen Gewerken",
    ausEinerHandText: "Elektroarbeiten sind an fast jeder Sanierung beteiligt. Renodex plant sie von Anfang an mit Trockenbau, Bad, Heizung und Malerarbeiten zusammen.",
    faqFrage: "Wird bei jeder Sanierung die komplette Elektrik erneuert?",
    faqAntwort: "Nein. Das hängt von Alter und Zustand der Installation ab. Fotos von Sicherungskasten und Leitungen reichen oft für eine erste Einschätzung. Ob eine Teil- oder Kompletterneuerung nötig ist, beurteilt die ausführende Elektro-Fachfirma.",
    weitereFragen: [
      { frage: "Was kostet eine Elektroinstallation in München?", antwort: "Die Preisübersicht von Renodex nennt für Elektroinstallation eine typische Spanne von 70 bis 105 Euro je Stunde. Was die Erneuerung insgesamt kostet, hängt von Fläche, Zahl der Stromkreise und davon ab, ob Wände geöffnet werden. Verbindlich ist erst der schriftliche Kostenvoranschlag." },
      { frage: "Wer prüft die neue Elektroinstallation?", antwort: "Die ausführende Elektro-Fachfirma prüft eine neue oder wesentlich geänderte Anlage vor der Inbetriebnahme. Gemessen werden unter anderem Schutzleiter, Isolation und die Auslösung der FI-Schutzschalter. Das Ergebnis wird in einem Prüfprotokoll festgehalten." },
      { frage: "Braucht jeder Raum einen eigenen Stromkreis?", antwort: "Nicht jeder Raum. Küche, Bad und Geräte mit hoher Leistung bekommen aber üblicherweise eigene abgesicherte Stromkreise. So legt ein Fehler nicht die ganze Wohnung lahm. Die genaue Aufteilung legt die Elektro-Fachfirma nach der geplanten Nutzung fest." },
      { frage: "Wird die Netzwerkverkabelung gleich mitgeplant?", antwort: "Das ist sinnvoll. Netzwerkleitungen und Leerrohre liegen in denselben Schlitzen wie die Stromleitungen. Werden sie im selben Zug verlegt, muss niemand frisch verputzte Wände ein zweites Mal öffnen." },
      { frage: "Wer führt die Elektroarbeiten aus?", antwort: "Eine eingetragene Elektro-Fachfirma. Den Vertrag über die Bauleistung schließen Sie wahlweise mit Renodex, auch als Gesamtpaket zu einem Festpreis, oder direkt mit der ausführenden Fachfirma. Renodex koordiniert in beiden Fällen Termine und Reihenfolge der Gewerke." },
    ],
    verwandteThemen: [
      { href: "/leistungen/photovoltaik", text: "Photovoltaik" },
      { href: "/leistungen/komplettsanierung", text: "Komplettsanierung" },
      { href: "/leistungen/waermepumpe", text: "Wärmepumpe" },
    ],
  },
  {
    slug: "sanitaer",
    title: "Sanitär",
    metaTitle: "Sanitär München – alte Wasserleitungen erneuern | Renodex",
    metaDescription: "Wasserdruck sinkt, Wasser kommt braun? Renodex koordiniert Sanitär-Fachfirmen in München. Laden Sie Fotos hoch und erhalten Sie eine Antwort per E-Mail.",
    heroFrage: "Sanitär in München: Wann müssen alte Wasserleitungen raus?",
    heroLead: "Der Wasserdruck lässt nach, nach dem Urlaub kommt braunes Wasser aus dem Hahn. Das deutet oft auf alte Leitungen hin. Eine eingetragene Sanitär-Fachfirma prüft und erneuert die Installation. Renodex koordiniert die Arbeiten mit Bad, Boden und Heizung.",
    heroImage: "/images/optimized/sanitaer-wasserleitung-waschbecken.webp",
    heroImageAlt: "Installateur schließt Wasserleitungen unter einem Waschbecken an",
    problemUeberschrift: "Woran erkennt man alte Wasserleitungen?",
    problemText: "Alte Leitungen sieht man selten, man merkt sie. Der Druck an der Dusche sinkt, weil sich die Rohre von innen zusetzen. Nach längerem Stillstand kommt rostbraunes Wasser. Wer bei einer Sanierung nur Fliesen und Armaturen tauscht, lässt dieses Risiko hinter der neuen Wand zurück.",
    loesungUeberschrift: "Wie läuft eine Sanitärerneuerung mit Renodex ab?",
    loesungPunkte: [
      "Sie schicken Fotos von Leitungen, Anschlüssen und Bad",
      "Eine eingetragene Sanitär-Fachfirma beurteilt den Zustand",
      "Erneuerung von Trink- und Abwasserleitungen nach Bedarf",
      "Renodex stimmt Sanitär, Fliesen und Boden aufeinander ab",
    ],
    vertiefungUeberschrift: "Welche Wasserleitungen müssen bei einer Sanierung erneuert werden?",
    vertiefungAbschnitte: [
      { titel: "Warum setzen sich verzinkte Stahlrohre zu?", text: "Verzinkte Stahlrohre wurden in Wohnhäusern bis etwa 1970 häufig verbaut. Über die Jahrzehnte lagern sich Kalk und Rost an der Innenwand ab. Der Querschnitt wird enger, der Wasserdruck sinkt. Rostbraunes Wasser nach längerem Stillstand ist ein typisches Zeichen. Wo verschiedene Metalle aufeinandertreffen, kann an den Übergängen zusätzlich Kontaktkorrosion entstehen." },
      { titel: "Was gilt für Bleileitungen im Trinkwasser?", text: "Die Trinkwasserverordnung von 2023 verlangt, dass Bleileitungen bis zum 12. Januar 2026 entfernt oder stillgelegt sind. Die Pflicht trifft den Betreiber der Trinkwasserinstallation, in der Regel den Eigentümer. Betroffen sind vor allem Altbauten, in denen die Leitungen nie erneuert wurden. Bleirohre sind grau, relativ weich und lassen sich mit einem Metallgegenstand leicht einritzen." },
      { titel: "Welche Rohre werden heute für Trinkwasser verbaut?", text: "Üblich sind heute Mehrschichtverbundrohre und Edelstahlrohre. Verbundrohre lassen sich gut biegen und dämpfen Fließgeräusche. Edelstahl ist sehr beständig und eignet sich für lange Leitungswege. Welches Material passt, hängt von der Verlegeart ab, also Aufputz, Unterputz oder Vorwand, und vom Zustand der vorhandenen Bausubstanz." },
    ],
    boxTitel: "Sanitärinstallation mit Bestandsschutz",
    ausEinerHandText: "Sanitärarbeiten sind bei Renodex eng mit Badsanierung, Heizung und Bodenverlegung verzahnt – alles aus einer Planung.",
    faqFrage: "Muss bei einer Badsanierung immer die komplette Sanitärinstallation erneuert werden?",
    faqAntwort: "Nein. Das hängt von Alter und Zustand der Leitungen ab. Fotos von Leitungen und Anschlüssen reichen oft für eine erste Einschätzung. Ob tatsächlich alles erneuert werden muss, beurteilt die ausführende Sanitär-Fachfirma.",
    weitereFragen: [
      { frage: "Kann man einzelne Rohrabschnitte sanieren oder muss immer die ganze Leitung erneuert werden?", antwort: "Bei punktuellen Schäden ist ein Teilaustausch möglich, sofern das übrige Leitungsnetz noch in ordnungsgemäßem Zustand ist. Bei durchgehender Verzinkung mit erkennbarer Korrosion über mehrere Stränge ist eine komplette Erneuerung sinnvoller, damit keine Altlast im System verbleibt, die die neuen Abschnitte belastet." },
      { frage: "Wird bei einer Sanitärsanierung auch die Heizung mit angefasst?", antwort: "Nein, die wasserführende Trinkwasserinstallation und die Heizungsanlage sind getrennte Gewerke mit eigenen Leitungsnetzen. Berührungspunkte wie gemeinsame Steigschächte oder ein Heizungstausch im selben Bauabschnitt werden bei Bedarf mit dem Heizungsgewerk abgestimmt." },
      { frage: "Muss für neue Rohrleitungen die Wand aufgestemmt werden?", antwort: "Bei Unterputzverlegung ja, hier werden Schlitze in Wand oder Boden gefräst und nach der Verlegung wieder verschlossen. Bei zugänglichen Bereichen wie Kellern oder Vorwandinstallationen lassen sich Leitungen dagegen oft ohne Stemmarbeiten verlegen." },
      { frage: "Was kostet Sanitärinstallation in München?", antwort: "Die Preisübersicht von Renodex nennt für Sanitärinstallation eine typische Spanne von 75 bis 110 Euro je Stunde. Was eine Erneuerung insgesamt kostet, hängt von Leitungslänge, Verlegeart und davon ab, ob Wände geöffnet werden. Verbindlich ist erst der schriftliche Kostenvoranschlag." },
      { frage: "Wer führt die Sanitärarbeiten aus?", antwort: "Eine eingetragene Sanitär-Fachfirma. Den Vertrag über die Bauleistung schließen Sie wahlweise mit Renodex, auch als Gesamtpaket zu einem Festpreis, oder direkt mit der ausführenden Fachfirma. Renodex koordiniert in beiden Fällen Termine und Reihenfolge der Gewerke." },
    ],
    verwandteThemen: [
      { href: "/leistungen/badsanierung", text: "Badsanierung" },
      { href: "/leistungen/heizung", text: "Heizung erneuern" },
      { href: "/wasserschaden", text: "Wasserschaden: was zuerst tun" },
    ],
  },
  {
    slug: "heizung",
    title: "Heizung",
    metaTitle: "Heizung erneuern München – Tausch & Beratung | Renodex",
    metaDescription: "Alter Kessel, hohe Heizkosten, unklare Alternative? Renodex koordiniert Fachfirmen für den Heizungstausch in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Heizung erneuern in München: Wann lohnt sich der Austausch?",
    heroLead: "Der Kessel ist alt, die Heizkosten steigen, und Sie wissen nicht, welches System zu Ihrem Haus passt. Eine eingetragene Heizungs-Fachfirma prüft die Anlage und plant den Tausch. Renodex koordiniert die beteiligten Gewerke.",
    heroImage: "/images/optimized/heizung-erneuern-heizungskeller.webp",
    heroImageAlt: "Heizungsbauer arbeitet an einem Wandheizgerät im Heizungskeller",
    problemUeberschrift: "Welche Heizung passt zu meinem Haus?",
    problemText: "Viele Eigentümer wissen, dass ihre Heizung nicht mehr zeitgemäß ist. Offen bleibt, welche Alternative zum Gebäude passt, etwa eine Wärmepumpe oder ein Brennwertgerät. Das hängt von Heizlast, Heizflächen und Dämmstandard ab. Deshalb steht vor jeder Empfehlung die Prüfung der vorhandenen Anlage.",
    loesungUeberschrift: "Wie läuft ein Heizungstausch mit Renodex ab?",
    loesungPunkte: [
      "Sie schicken Fotos von Kessel, Typenschild und Heizkörpern",
      "Eine eingetragene Heizungs-Fachfirma prüft die Anlage",
      "Beratung zu passenden Alternativen für Ihr Gebäude",
      "Renodex stimmt Heizung, Sanitär und Elektro aufeinander ab",
    ],
    vertiefungUeberschrift: "Wann muss eine alte Heizung ausgetauscht werden?",
    vertiefungAbschnitte: [
      { titel: "Gibt es eine Austauschpflicht für alte Heizkessel?", text: "Nach § 72 Gebäudeenergiegesetz müssen Öl- und Gaskessel mit Konstanttemperatur-Technik nach 30 Jahren außer Betrieb. Brennwert- und Niedertemperaturkessel sind ausgenommen. Ausgenommen sind auch Eigentümer, die ihr Ein- oder Zweifamilienhaus seit dem 1. Februar 2002 selbst bewohnen. Nach einem Eigentümerwechsel hat der neue Eigentümer für den Austausch zwei Jahre Zeit." },
      { titel: "Warum gehört der hydraulische Abgleich zum Heizungstausch?", text: "Beim hydraulischen Abgleich stellt die Fachfirma jeden Heizkörper auf die Wassermenge ein, die sein Raum braucht. Ohne Abgleich bekommen Heizkörper nahe am Kessel zu viel Wasser, entfernte Räume bleiben kühl. Die Pumpe läuft dann stärker als nötig. Förderprogramme für den Heizungstausch verlangen den Abgleich in der Regel." },
      { titel: "Passen die alten Heizkörper zur neuen Anlage?", text: "Alte Heizkörper sind oft für hohe Vorlauftemperaturen ausgelegt. Eine neue Anlage, besonders eine Wärmepumpe, arbeitet mit niedrigen Temperaturen effizienter. Dann reicht die Fläche mancher Heizkörper nicht mehr aus. Die Fachfirma berechnet raumweise, welche Heizkörper bleiben können und welche gegen größere getauscht werden sollten." },
    ],
    boxTitel: "Heizungstechnik nach Bestand und Bedarf",
    ausEinerHandText: "Ein Heizungstausch wird bei Renodex oft gemeinsam mit Sanitär- und Elektroarbeiten geplant, insbesondere wenn eine Wärmepumpe vorgesehen ist.",
    faqFrage: "Berät Renodex auch zur Wärmepumpe als Alternative?",
    faqAntwort: "Ja. Die Heizungs-Fachfirma prüft anhand von Heizlast, Heizflächen und Dämmstandard, ob eine Wärmepumpe für Ihr Gebäude passt. Passt sie nicht, nennt sie die Alternative.",
    weitereFragen: [
      { frage: "Kann die Heizung während der Sanierung weiterlaufen?", antwort: "Bei einem reinen Kesseltausch werden die vorhandenen Heizkörper und Leitungen weitergenutzt. Die Heizung steht nur für den Tausch selbst still. Wird zusätzlich das Verteilnetz erneuert, muss die Heizung für den betroffenen Zeitraum abgestellt werden. Den Ablauf stimmen wir vorab mit Ihnen ab, besonders in der Heizperiode." },
      { frage: "Welche Unterlagen werden für ein Angebot zur Heizungsanlage benötigt?", antwort: "Hilfreich sind Fotos des bestehenden Kessels und der Heizkörper, Angaben zur Wohn-/Nutzfläche und, falls vorhanden, alte Wartungsprotokolle oder der Energieausweis. Diese Unterlagen können direkt über den digitalen Kontaktweg hochgeladen werden, eine Vorab-Besichtigung ist dafür nicht zwingend nötig." },
      { frage: "Wird bei der Heizungssanierung auch die Warmwasserbereitung mit einbezogen?", antwort: "Wenn der Kessel auch die Warmwasserbereitung übernimmt, wird das bei der Planung berücksichtigt, damit die neue Anlage beide Aufgaben zuverlässig abdeckt. Reine Sanitärleitungen und Armaturen sind kein Bestandteil der Heizungsarbeiten und werden bei Bedarf mit dem Sanitärgewerk abgestimmt." },
      { frage: "Was kostet eine neue Heizung in München?", antwort: "Das hängt vom System, der Heizlast und dem Umbauaufwand ab. Für einen Heizungstausch auf Wärmepumpe nennt die Preisübersicht von Renodex eine typische Spanne von 12.000 bis 25.000 Euro als Pauschale. Verbindlich ist erst das Festpreisangebot, das Renodex nach der Besichtigung erstellt." },
      { frage: "Muss ein Heizkessel nach 30 Jahren raus?", antwort: "Bei Öl- und Gaskesseln mit Konstanttemperatur-Technik in der Regel ja (§ 72 GEG). Brennwert- und Niedertemperaturkessel sind ausgenommen. Ausgenommen sind auch Eigentümer, die ihr Ein- oder Zweifamilienhaus seit dem 1. Februar 2002 selbst bewohnen." },
    ],
    verwandteThemen: [
      { href: "/leistungen/waermepumpe", text: "Wärmepumpe" },
      { href: "/leistungen/sanitaer", text: "Sanitär" },
      { href: "/leistungen/photovoltaik", text: "Photovoltaik" },
    ],
  },
  {
    slug: "waermepumpe",
    title: "Wärmepumpe",
    metaTitle: "Wärmepumpe München – Eignung prüfen & Einbau | Renodex",
    metaDescription: "Passt eine Wärmepumpe zu Ihrem Haus? Renodex koordiniert Fachfirmen für Prüfung und Einbau in München. Fotos Ihrer Heizung hochladen, Antwort per E-Mail.",
    heroFrage: "Wärmepumpe in München: Passt sie zu meinem Haus?",
    heroLead: "Sie haben viel über Wärmepumpen gelesen, aber wenig davon passt genau zu Ihrem Haus. Ob sie sich lohnt, hängt von Heizflächen, Dämmung und Grundstück ab. Eine eingetragene Fachfirma prüft das und baut die Anlage ein. Renodex koordiniert Heizung, Elektro und Sanitär.",
    heroImage: "/images/optimized/waermepumpe-aussengeraet-montage.webp",
    heroImageAlt: "Monteur schließt das Außengerät einer Luft-Wasser-Wärmepumpe an",
    problemUeberschrift: "Lohnt sich eine Wärmepumpe im Altbau?",
    problemText: "Zur Wärmepumpe gibt es viele pauschale Aussagen. Für den Altbau stimmen sie selten ohne Einschränkung. Manche unsanierten Häuser eignen sich gut, andere erst nach einzelnen Maßnahmen an Dämmung oder Heizkörpern. Die Antwort liefert die berechnete Heizlast Ihres Gebäudes.",
    loesungUeberschrift: "Wie wird geprüft, ob eine Wärmepumpe passt?",
    loesungPunkte: [
      "Sie schicken Fotos von Heizung, Heizkörpern und möglichem Aufstellort",
      "Eine eingetragene Fachfirma prüft Heizlast und Vorlauftemperatur",
      "Offene Einschätzung, auch wenn eine andere Lösung besser passt",
      "Renodex stimmt Heizung, Elektro und Sanitär aufeinander ab",
    ],
    vertiefungUeberschrift: "Welche Voraussetzungen braucht eine Wärmepumpe?",
    vertiefungAbschnitte: [
      { titel: "Welche Vorlauftemperatur braucht eine Wärmepumpe?", text: "Eine Wärmepumpe arbeitet umso effizienter, je niedriger die Vorlauftemperatur ist. Fußboden- und Wandheizungen kommen mit niedrigen Temperaturen aus und passen gut. Klassische Heizkörper brauchen oft mehr Wärme. Hier prüft die Fachfirma raumweise, ob die Fläche reicht oder einzelne Heizkörper größer werden müssen." },
      { titel: "Was sagt die Jahresarbeitszahl einer Wärmepumpe?", text: "Die Jahresarbeitszahl gibt an, wie viel Wärme eine Wärmepumpe über ein Jahr aus einer Kilowattstunde Strom erzeugt. Je höher der Wert, desto weniger Strom braucht sie für dieselbe Wärme. Die Zahl hängt vom Gerät ab, genauso aber von Vorlauftemperatur, Heizlast und Wärmequelle des jeweiligen Gebäudes." },
      { titel: "Luft oder Erdwärme: Welche Wärmepumpe passt aufs Grundstück?", text: "Luft-Wasser-Wärmepumpen kommen ohne Erdarbeiten aus. Das Außengerät braucht einen Aufstellort, an dem die Grenzwerte der TA Lärm zum Nachbarn eingehalten werden. Erdwärmepumpen mit Sonde arbeiten übers Jahr gleichmäßiger. Für die Bohrung ist eine wasserrechtliche Erlaubnis nötig, und das Bohrgerät muss aufs Grundstück kommen." },
    ],
    boxTitel: "Wärmepumpe: Eignung vor Angebot",
    ausEinerHandText: "Die Installation einer Wärmepumpe wird bei Renodex mit den Elektro- und Sanitärarbeiten der Sanierung zusammen geplant.",
    faqFrage: "Ist eine Wärmepumpe auch in einem Altbau sinnvoll?",
    faqAntwort: "Oft ja. Entscheidend sind Dämmstandard, Heizflächen und die berechnete Heizlast. Fotos der Heizung und Angaben zum Haus reichen für eine erste Einschätzung. Ob eine Wärmepumpe passt oder eine andere Lösung sinnvoller ist, beurteilt die Fachfirma.",
    weitereFragen: [
      { frage: "Kann eine Wärmepumpe auch im Altbau ohne Dämmung nachgerüstet werden?", antwort: "Grundsätzlich ja, die Wirtschaftlichkeit hängt aber vom erreichbaren Vorlauftemperaturniveau ab. Bei sehr hohem Wärmebedarf wird häufig eine Kombination aus punktueller Dämmmaßnahme und Wärmepumpe geprüft, damit die Anlage im wirtschaftlichen Betriebsbereich läuft." },
      { frage: "Muss die alte Heizung komplett raus, wenn eine Wärmepumpe eingebaut wird?", antwort: "Nicht zwingend. In einer Übergangsphase ist ein bivalenter Betrieb mit der bestehenden Heizquelle möglich, etwa an sehr kalten Tagen. Ob das sinnvoll ist oder ein vollständiger Ersatz angestrebt wird, hängt vom Zustand der Altanlage und der Heizlastberechnung ab." },
      { frage: "Wie laut ist eine Luft-Wasser-Wärmepumpe im Betrieb?", antwort: "Die Schallemission hängt vom Gerätetyp und der Aufstellung ab und unterliegt an der Grundstücksgrenze den Grenzwerten der TA Lärm. Der Aufstellort wird deshalb so gewählt und ausgerichtet, dass diese Werte eingehalten werden, insbesondere bei geringem Abstand zur Nachbarbebauung." },
      { frage: "Was kostet eine Wärmepumpe in München?", antwort: "Die Preisübersicht von Renodex nennt für einen Heizungstausch auf Wärmepumpe eine typische Spanne von 12.000 bis 25.000 Euro als Pauschale. Wo es im Einzelfall liegt, hängt von Wärmequelle, Heizlast und nötigen Anpassungen an Heizkörpern und Elektrik ab. Verbindlich ist erst der schriftliche Kostenvoranschlag." },
      { frage: "Gibt es Förderung für eine Wärmepumpe?", antwort: "Der Heizungstausch auf eine Wärmepumpe wird über die Bundesförderung für effiziente Gebäude (BEG) unterstützt, für Wohngebäude über die KfW. Der Antrag muss in der Regel gestellt sein, bevor das Vorhaben beginnt. Die Bedingungen ändern sich. Maßgeblich ist der aktuelle Stand bei der KfW." },
    ],
    verwandteThemen: [
      { href: "/leistungen/heizung", text: "Heizung erneuern" },
      { href: "/leistungen/photovoltaik", text: "Photovoltaik" },
      { href: "/leistungen/elektroinstallation", text: "Elektroinstallation" },
    ],
  },
  {
    slug: "photovoltaik",
    title: "Photovoltaik",
    metaTitle: "Photovoltaik München – Dach prüfen & Anlage planen | Renodex",
    metaDescription: "Lohnt sich Solarstrom auf Ihrem Dach? Renodex koordiniert Fachfirmen für Prüfung und Montage in München. Fotos vom Dach hochladen, Antwort per E-Mail.",
    heroFrage: "Photovoltaik in München: Lohnt sich eine Anlage auf meinem Dach?",
    heroLead: "Die Stromrechnung steigt, und auf dem Dach liegt ungenutzte Fläche. Ob sich eine Photovoltaikanlage rechnet, hängt von Ausrichtung, Verschattung und Ihrem Verbrauch ab. Eine eingetragene Fachfirma prüft das und montiert die Anlage. Renodex koordiniert Elektro, Wärmepumpe und die übrigen Gewerke.",
    heroImage: "/images/optimized/photovoltaik-montage-ziegeldach-muenchen.webp",
    heroImageAlt: "Monteur befestigt Solarmodule auf Schienen eines Ziegeldachs",
    problemUeberschrift: "Ist mein Dach für Photovoltaik geeignet?",
    problemText: "Pauschale Ertragsversprechen helfen bei dieser Frage wenig. Ein Süddach mit Schatten vom Nachbarhaus bringt unter Umständen weniger als eine freie Ost-West-Fläche. Dazu kommt der Zustand der Dacheindeckung. Muss sie ohnehin bald erneuert werden, gehört das vor der Montage geklärt.",
    loesungUeberschrift: "Wie läuft eine Photovoltaik-Anfrage mit Renodex ab?",
    loesungPunkte: [
      "Sie schicken Fotos vom Dach, vom Zählerschrank und Ihre Stromrechnung",
      "Eine eingetragene Fachfirma prüft Dachfläche, Verschattung und Verbrauch",
      "Planung von Anlage, Wechselrichter und auf Wunsch Speicher",
      "Renodex stimmt Photovoltaik, Elektro und Wärmepumpe aufeinander ab",
    ],
    vertiefungUeberschrift: "Was entscheidet über den Nutzen einer Photovoltaikanlage?",
    vertiefungAbschnitte: [
      { titel: "Welche Dachausrichtung eignet sich für Photovoltaik?", text: "Süddächer liefern um die Mittagszeit die höchste Leistung. Ost-West-Dächer verteilen den Ertrag gleichmäßiger auf Vormittag und Nachmittag. Das passt oft besser zum Verbrauch im Haushalt. Genauso wichtig ist die Verschattung durch Gauben, Kamine, Bäume oder Nachbargebäude. Die Fachfirma bewertet deshalb die ganze Dachfläche, nicht nur die Himmelsrichtung." },
      { titel: "Warum zählt der Eigenverbrauch?", text: "Selbst genutzter Solarstrom ersetzt Strom, den Sie sonst beim Versorger kaufen. Für eingespeisten Strom gibt es eine Vergütung nach dem Erneuerbare-Energien-Gesetz, die in der Regel unter dem Bezugspreis liegt. Wärmepumpe, Wallbox oder Batteriespeicher erhöhen den selbst verbrauchten Anteil. Ihre Stromrechnungen zeigen, welche Kombination zu Ihrem Haushalt passt." },
      { titel: "Was muss vor dem Betrieb angemeldet werden?", text: "Eine Photovoltaikanlage wird beim örtlichen Netzbetreiber angemeldet, bevor sie Strom ins Netz einspeist. Zusätzlich ist sie im Marktstammdatenregister der Bundesnetzagentur einzutragen. Oft muss der Zählerschrank angepasst oder ein neuer Zähler gesetzt werden. Den Netzanschluss übernimmt eine eingetragene Elektro-Fachfirma. Die genauen Vorgaben nennt Ihr Netzbetreiber." },
    ],
    boxTitel: "Photovoltaik zusammen mit Elektro und Heizung geplant",
    ausEinerHandText: "Photovoltaik wird bei Renodex mit Elektroinstallation und Wärmepumpe zusammen geplant. So passen Zählerschrank, Leitungswege und Verbrauch von Anfang an zueinander.",
    faqFrage: "Lohnt sich Photovoltaik auch auf einem Ost-West-Dach?",
    faqAntwort: "Oft ja. Ein Ost-West-Dach erzeugt über einen längeren Teil des Tages Strom. Das kann den Eigenverbrauch erhöhen. Ob es sich für Ihr Haus rechnet, beurteilt die Fachfirma anhand von Dachfotos, Verschattung und Stromverbrauch.",
    weitereFragen: [
      { frage: "Brauche ich einen Batteriespeicher?", antwort: "Nicht zwingend. Ein Speicher verschiebt Solarstrom vom Tag in den Abend und erhöht so den Eigenverbrauch. Ob sich die Mehrkosten lohnen, hängt davon ab, wann Sie Strom brauchen. Die Fachfirma rechnet beide Varianten anhand Ihres Verbrauchs durch." },
      { frage: "Muss das Dach vor der Montage saniert werden?", antwort: "Das hängt vom Zustand der Eindeckung ab. Steht eine Dachsanierung ohnehin an, ist sie vor der Montage meist sinnvoller. Sonst müssen die Module später wieder herunter. Das klärt die Prüfung anhand Ihrer Dachfotos." },
      { frage: "Was kostet eine Photovoltaikanlage in München?", antwort: "Das hängt von Anlagengröße, Speicher und dem Aufwand am Zählerschrank ab. Die Preisübersicht von Renodex führt die Erstberatung zur Photovoltaik als kostenlos. Verbindlich ist erst das Festpreisangebot, das Renodex nach der Besichtigung erstellt." },
      { frage: "Passt Photovoltaik zu einer Wärmepumpe?", antwort: "Ja, beide ergänzen sich. Die Wärmepumpe nutzt einen Teil des Solarstroms direkt. Im Winter braucht sie am meisten Strom, während die Anlage weniger liefert. Die Fachfirma plant beides deshalb gemeinsam und zeigt, welchen Anteil der Solarstrom realistisch abdeckt." },
      { frage: "Wer führt die Photovoltaik-Arbeiten aus?", antwort: "Eingetragene Fachfirmen für Montage und Elektroanschluss. Den Vertrag über die Bauleistung schließen Sie wahlweise mit Renodex, auch als Gesamtpaket zu einem Festpreis, oder direkt mit der ausführenden Fachfirma. Renodex koordiniert in beiden Fällen Termine und Reihenfolge der Gewerke." },
    ],
    verwandteThemen: [
      { href: "/leistungen/waermepumpe", text: "Wärmepumpe" },
      { href: "/leistungen/elektroinstallation", text: "Elektroinstallation" },
      { href: "/leistungen/heizung", text: "Heizung erneuern" },
    ],
  },
  {
    slug: "innenausbau",
    title: "Innenausbau",
    metaTitle: "Innenausbau München – Gewerke im richtigen Takt | Renodex",
    metaDescription: "Mehrere Gewerke, aber niemand hält die Reihenfolge zusammen? Renodex koordiniert den Innenausbau in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Innenausbau in München: Warum entscheidet die Reihenfolge der Gewerke?",
    heroLead: "Beim Innenausbau hängt jedes Gewerk vom vorherigen ab – wird ein Schritt zu früh oder zu spät beauftragt, entstehen Wartezeiten oder bereits fertige Arbeit muss wieder geöffnet werden. Renodex übernimmt genau diese Koordination: die Abstimmung der beteiligten Partnerbetriebe zu einem funktionierenden Bauablauf.",
    heroImage: "/images/optimized/innenausbau-leitungen-verlegen-rohbau.webp",
    heroImageAlt: "Elektriker und Installateur verlegen Leitungen im entkernten Raum",
    problemUeberschrift: "Ohne Ablaufplan entstehen Wartezeiten und doppelte Arbeit",
    problemText: "Wer mehrere Gewerke einzeln beauftragt, trägt selbst die Verantwortung für die richtige Reihenfolge und die Übergabe zwischen den Handwerkern. Fehlt eine verbindliche Abstimmung, stehen Gewerke ungenutzt auf der Baustelle, während andere auf ihre Vorleistung warten – oder ein Gewerk beginnt, bevor die Voraussetzung dafür überhaupt geschaffen ist.",
    loesungUeberschrift: "Ein Ablaufplan mit klaren Übergaben zwischen den Gewerken",
    loesungPunkte: [
      "Ein Bauablaufplan mit Reihenfolge und Zeitfenstern je Gewerk",
      "Freigabe der Vorleistung, bevor das nächste Gewerk beginnt",
      "Ein Ansprechpartner für alle beteiligten Partnerbetriebe",
      "Regelmäßige Abstimmung statt einmaliger Terminzusage",
    ],
    vertiefungUeberschrift: "Wie koordiniert RENODEX mehrere Gewerke beim Innenausbau?",
    vertiefungAbschnitte: [
      { titel: "Was gehört zu einem belastbaren Bauablaufplan?", text: "Ein belastbarer Bauablaufplan legt nicht nur Kalenderdaten fest, sondern die Bedingungen, unter denen ein Gewerk mit seiner Arbeit beginnen darf – etwa dass die Vorleistung geprüft und freigegeben ist, bevor das nächste Gewerk anrückt. Reine Terminlisten ohne diese Abhängigkeiten sind fehleranfällig, sobald sich ein Schritt verschiebt." },
      { titel: "Wie werden Verzögerungen bei einem Gewerk aufgefangen?", text: "Verschiebt sich ein Gewerk, wirkt sich das auf alle nachfolgenden Schritte aus, wenn der Ablaufplan keine Pufferzeiten an den kritischen Übergängen vorsieht. RENODEX plant diese Puffer ein und stimmt sich bei Verzögerungen mit den betroffenen Partnerbetrieben ab, damit sich die Verschiebung nicht ungebremst durch den gesamten Bauablauf zieht." },
      { titel: "Wer prüft, ob ein Gewerk seine Arbeit ordnungsgemäß übergeben hat?", text: "An jeder Schnittstelle zwischen zwei Gewerken steht eine Übergabe: das vorangegangene Gewerk muss seine Leistung in einem Zustand hinterlassen, auf dem der nächste Schritt sauber aufsetzen kann. RENODEX koordiniert diese Übergaben zwischen den beteiligten Partnerbetrieben, statt sie den Kunden selbst nachhalten zu lassen." },
    ],
    boxTitel: "Koordination statt Einzelabsprachen mit jedem Gewerk",
    ausEinerHandText: "Innenausbau-Koordination wird bei Renodex häufig im Rahmen einer Komplettsanierung beauftragt, kann aber auch für ein einzelnes Vorhaben mit mehreren Gewerken gebucht werden – die Einzelleistungen selbst finden Sie auf den jeweiligen Gewerke-Seiten.",
    faqFrage: "Ab wie vielen Gewerken lohnt sich eine koordinierte Ablaufplanung?",
    faqAntwort: "Schon ab zwei aufeinander aufbauenden Gewerken lohnt sich eine abgestimmte Reihenfolge, weil sonst Wartezeiten oder Doppelarbeit entstehen können. Renodex bespricht im Erstgespräch, welche Gewerke im konkreten Vorhaben beteiligt sind und wie die Reihenfolge sinnvoll aussieht.",
    weitereFragen: [
      { frage: "Übernimmt Renodex auch die einzelnen Gewerke selbst?", antwort: "Nein, die handwerkliche Ausführung der einzelnen Gewerke übernehmen die jeweiligen Fachfirmen aus unserem Netzwerk, mit denen Sie einen eigenen Vertrag schließen. Renodex koordiniert die Abstimmung zwischen den Gewerken." },
      { frage: "Was passiert, wenn während der Arbeiten ein weiteres Gewerk nötig wird?", antwort: "Stellt sich während des laufenden Innenausbaus heraus, dass ein zusätzliches Gewerk gebraucht wird, wird das in den bestehenden Ablaufplan eingeordnet und mit den bereits beauftragten Partnerbetrieben zeitlich abgestimmt." },
      { frage: "Wie oft findet eine Abstimmung zwischen den Gewerken statt?", antwort: "Das hängt vom Umfang des Vorhabens ab – bei mehreren parallel laufenden Gewerken sind regelmäßige, meist wöchentliche Abstimmungen üblich, damit Verzögerungen frühzeitig auffallen und nicht erst am geplanten Übergabetermin." },
    ],

  },
  {
    slug: "trockenbau",
    title: "Trockenbau",
    metaTitle: "Trockenbau München – Wände, Decken, Ständerwerk | Renodex",
    metaDescription: "Neue Wand, abgehängte Decke oder andere Raumaufteilung? Renodex koordiniert Trockenbau-Fachfirmen in München. Fotos hochladen, Antwort per E-Mail.",
    heroFrage: "Trockenbau in München: Wofür wird er eingesetzt?",
    heroLead: "Trockenbau schafft mit Ständerwerk und Gipskarton neue Wände, abgehängte Decken oder eine veränderte Raumaufteilung – ohne die aufwendigen Trocknungszeiten einer massiven Bauweise. Renodex setzt Trockenbau als eigenständiges Gewerk oder als ersten Schritt eines Innenausbaus um.",
    heroImage: "/images/optimized/trockenbau-gipskarton-metallstaender.webp",
    heroImageAlt: "Trockenbauer verschraubt Gipskartonplatten auf dem Metallständerwerk",
    problemUeberschrift: "Der erste Schritt, der alle folgenden Gewerke beeinflusst",
    problemText: "Trockenbauwände legen fest, wo später Steckdosen, Leitungen und Anschlüsse liegen können. Wird der Trockenbau ohne Abstimmung mit Elektro und Sanitär geplant, müssen Wände nachträglich wieder geöffnet werden.",
    loesungUeberschrift: "Trockenbau abgestimmt mit den Folgegewerken",
    loesungPunkte: [
      "Ständerwerk und Beplankung für Wände und Decken",
      "Planung der Wanddurchbrüche für Elektro und Sanitär vorab",
      "Schall- und Brandschutzanforderungen je nach Raum berücksichtigt",
      "Nahtlose Übergabe an Elektro, Maler und Fliesenleger",
    ],
    vertiefungUeberschrift: "Wie läuft eine Trockenbau-Maßnahme bei einer Sanierung ab?",
    vertiefungAbschnitte: [
      { titel: "Welche Schritte umfasst der Trockenbau vor den Folgegewerken?", text: "Der Trockenbau beginnt mit der Planung des Ständerwerks aus Metallprofilen, gefolgt von der Beplankung mit Gipskarton- oder Gipsfaserplatten. Bei tragenden Anschlüssen und Deckenabhängungen wird die Statik berücksichtigt, bei Bädern und Feuchträumen kommen feuchtraumbeständige Platten zum Einsatz. Leitungsführungen für Elektro und Sanitär werden vorab mit den jeweiligen Gewerken abgestimmt, damit die Wand erst nach Fertigstellung der Installationsebene geschlossen wird." },
      { titel: "Welche Bauteile werden im Trockenbau unterschieden?", text: "Man unterscheidet nichttragende Trennwände, Vorsatzschalen zur Wandverkleidung, abgehängte Decken zur Verlegung von Leitungen oder zur Raumakustik sowie Dachschrägenverkleidungen im ausgebauten Dachgeschoss. Jede Bauteilart hat eigene Anforderungen an Profiltiefe, Dämmung und Beplankungsstärke, abhängig von Schall- und Brandschutzvorgaben laut DIN 4109 bzw. DIN 4102." },
      { titel: "Wie wird der Schallschutz im Trockenbau sichergestellt?", text: "Der Schallschutz einer Trockenbauwand hängt von der Anzahl der Beplankungslagen, der Dämmstoffeinlage im Ständerwerk und der Entkopplung von der Rohbaukonstruktion ab. Doppelständerwände mit getrennten Profilschienen reduzieren die Schallübertragung stärker als einfache Ständerwände. Die Ausführung richtet sich nach der Nutzung der angrenzenden Räume, etwa bei Schlafzimmern oder Mehrfamilienhäusern." },
    ],
    boxTitel: "Trockenbau als Grundlage für den Innenausbau",
    ausEinerHandText: "Trockenbau ist bei Renodex häufig der erste Schritt eines Innenausbaus, kann aber auch als eigenständiges Vorhaben beauftragt werden – etwa für eine neue Raumaufteilung ohne größere Sanierung.",
    faqFrage: "Ist Trockenbau eine Alternative zu einer massiven Wand?",
    faqAntwort: "Für nichttragende Innenwände ja – Trockenbau ist schneller umgesetzt und ohne lange Trocknungszeiten. Tragende Wände lassen sich damit nicht ersetzen, hier bleibt die massive Bauweise erforderlich.",
    weitereFragen: [
      { frage: "Kann Trockenbau auch nachträglich in bewohnten Räumen erfolgen?", antwort: "Trockenbauarbeiten sind grundsätzlich auch im bewohnten Zustand möglich, da sie im Vergleich zu Maurerarbeiten staub- und lärmärmer ablaufen. Angrenzende Räume werden während der Bauphase mit Staubschutzwänden abgetrennt, eine vollständige Freiräumung ist meist nur im direkt betroffenen Raum nötig." },
      { frage: "Welche Vorarbeiten sind vor dem Trockenbau nötig?", antwort: "Vor dem Aufbau des Ständerwerks müssen Boden und Decke tragfähig und eben sein, alte Putz- oder Tapetenreste im Anschlussbereich entfernt werden. Bestehende Leitungen im Wandbereich werden erfasst, damit die neue Trennwand nicht in bestehende Elektro- oder Sanitärführungen einbindet." },
      { frage: "Wie wird die Oberfläche einer Trockenbauwand für den Anstrich vorbereitet?", antwort: "Nach der Beplankung werden die Plattenstöße gespachtelt, mit Fugenband armiert und geschliffen, üblich sind hierfür die Qualitätsstufen Q2 bis Q4 je nach Anforderung an die Oberfläche. Erst nach vollständiger Trocknung und Grundierung ist die Wand bereit für Maler- oder Tapezierarbeiten, die als eigenes Gewerk folgen." },
    ],

  },
];
