export interface LeistungThema {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  heroFrage: string;
  heroLead: string;
  problemUeberschrift: string;
  problemText: string;
  loesungUeberschrift: string;
  loesungPunkte: string[];
  ausEinerHandText: string;
  faqFrage: string;
  faqAntwort: string;
}

export const LEISTUNGEN_THEMEN: LeistungThema[] = [
  {
    slug: "komplettsanierung",
    title: "Komplettsanierung",
    metaTitle: "Komplettsanierung München – Haus & Wohnung aus einer Hand | Renodex",
    metaDescription: "Komplettsanierung in München und Umgebung im Umkreis von 25 km: Sanierung, Renovierung, Elektro, Sanitär, Heizung – alles aus einer Hand mit Renodex.",
    heroFrage: "Was ist eine Komplettsanierung – und wann lohnt sie sich?",
    heroLead: "Eine Komplettsanierung fasst alle Gewerke einer Haus- oder Wohnungssanierung unter einer Planung zusammen – von der Elektroinstallation über Sanitär und Heizung bis zu Böden, Malerarbeiten und Dach. Statt fünf Handwerker einzeln zu koordinieren, übernimmt Renodex die gesamte Abstimmung.",
    problemUeberschrift: "Mehrere Gewerke, ein Terminplan – und ständig Abstimmungsbedarf",
    problemText: "Wer Haus oder Wohnung umfassend sanieren will, steht schnell vor derselben Herausforderung: Elektriker, Sanitärinstallateur, Maler und Bodenleger arbeiten selten aufeinander abgestimmt. Termine verschieben sich, Gewerke behindern sich gegenseitig, und die Verantwortung für das Gesamtergebnis liegt am Ende bei niemandem so richtig.",
    loesungUeberschrift: "Eine Ansprechperson, ein Zeitplan, ein Ergebnis",
    loesungPunkte: [
      "Ein fester Ansprechpartner für die gesamte Sanierung",
      "Abgestimmter Zeitplan für alle beteiligten Gewerke",
      "Elektro, Sanitär, Heizung, Böden und Malerarbeiten aus einer Planung",
      "Regelmäßige Rücksprache statt Einzelabsprachen mit jedem Gewerk",
    ],
    ausEinerHandText: "Eine Komplettsanierung betrifft in der Regel Haus und Wohnung gleichermaßen – deshalb koordiniert Renodex auf Wunsch auch Dach, Fassade und Mauerwerksabdichtung mit, wenn diese Teil des Vorhabens sind.",
    faqFrage: "Was kostet eine Komplettsanierung in München?",
    faqAntwort: "Die Kosten hängen vom Umfang der Arbeiten, dem Zustand der Bausubstanz und den gewünschten Gewerken ab. Nach einer Besichtigung erstellt Renodex ein transparentes Angebot mit allen enthaltenen Leistungen, bevor die Arbeiten beginnen.",
  },
  {
    slug: "haussanierung",
    title: "Haussanierung",
    metaTitle: "Haussanierung München – Einfamilienhaus sanieren | Renodex",
    metaDescription: "Haussanierung in München und Umgebung (25 km Radius): Bausubstanz, Technik und Optik aus einer Hand modernisieren – mit Renodex.",
    heroFrage: "Wann wird die Sanierung eines Hauses notwendig?",
    heroLead: "Ein Haus im Bestand zeigt seinen Sanierungsbedarf meist schleichend: veraltete Elektrik, ineffiziente Heizung, undichte Fenster oder ein Dach, das die nächsten Winter nicht mehr übersteht. Renodex saniert Häuser ganzheitlich – Technik, Substanz und Optik gemeinsam gedacht.",
    problemUeberschrift: "Veraltete Technik, unklarer Zustand, keine Übersicht über die Reihenfolge",
    problemText: "Bei einem älteren Haus stellt sich oft nicht nur die Frage, was saniert werden muss, sondern auch in welcher Reihenfolge – Elektrik vor Wänden, Heizung vor Böden, Dach vor Dämmung. Ohne fachliche Planung entstehen teure Umwege oder Arbeiten, die später wieder geöffnet werden müssen.",
    loesungUeberschrift: "Sanierungsreihenfolge aus einer erfahrenen Hand",
    loesungPunkte: [
      "Bestandsaufnahme der Bausubstanz vor Planungsbeginn",
      "Sinnvolle Reihenfolge der Gewerke, damit nichts doppelt geöffnet wird",
      "Elektro, Sanitär, Heizung, Dach und Fassade aus einer Koordination",
      "Werterhalt der Immobilie als Planungsgrundlage",
    ],
    ausEinerHandText: "Da eine Haussanierung meist mehrere Gewerke gleichzeitig betrifft, ist sie ein klassisches Beispiel für die Renodex-Positionierung: Komplettsanierung aus einer Hand statt Einzelvergabe an verschiedene Betriebe.",
    faqFrage: "Wie lange dauert eine Haussanierung?",
    faqAntwort: "Die Dauer hängt vom Umfang ab – eine einzelne Gewerkesanierung ist schneller abgeschlossen als eine Komplettsanierung mit mehreren Bauabschnitten. Renodex nennt nach der Besichtigung einen realistischen Zeitrahmen für das konkrete Vorhaben.",
  },
  {
    slug: "wohnungssanierung",
    title: "Wohnungssanierung",
    metaTitle: "Wohnungssanierung München – Sanierung & Renovierung | Renodex",
    metaDescription: "Wohnungssanierung und Wohnungsrenovierung in München und Umgebung: Bad, Böden, Elektro und Heizung aus einer Hand – mit Renodex.",
    heroFrage: "Was gehört zu einer Wohnungssanierung dazu?",
    heroLead: "Eine Wohnungssanierung reicht von der Erneuerung einzelner Räume bis zur kompletten Modernisierung – häufig ausgelöst durch einen Eigentümerwechsel, eine Vermietung oder den Wunsch, veraltete Technik zeitgemäß zu ersetzen. Renodex saniert Wohnungen unter laufender Terminplanung und mit möglichst wenig Beeinträchtigung für die Bewohner.",
    problemUeberschrift: "Renovieren in bewohnten Räumen, mit begrenztem Zeitfenster",
    problemText: "In einer Wohnung lässt sich selten monatelang bauen – oft muss ein Bad, eine Küche oder ein ganzer Wohnbereich in einem klar begrenzten Zeitfenster fertig werden, während der Alltag weiterläuft oder ein Mieterwechsel ansteht.",
    loesungUeberschrift: "Planbare Sanierung mit festem Zeitrahmen",
    loesungPunkte: [
      "Klar terminierte Bauabschnitte statt offenem Zeitrahmen",
      "Bad, Böden, Elektro und Heizung aus einer Hand koordiniert",
      "Abstimmung mit Eigentümer, Hausverwaltung oder Mieter",
      "Saubere Übergabe nach Fertigstellung",
    ],
    ausEinerHandText: "Ob Haus oder Wohnung – die Koordination aus einer Hand ist bei Renodex derselbe Ansatz: ein Ansprechpartner für alle beteiligten Gewerke.",
    faqFrage: "Kann eine Wohnung während der Sanierung bewohnt bleiben?",
    faqAntwort: "Das hängt vom Umfang der Arbeiten ab. Bei einzelnen Gewerken ist ein Verbleib oft möglich, bei einer Komplettsanierung empfiehlt sich meist ein vorübergehender Auszug. Renodex bespricht das im Vorfeld transparent.",
  },
  {
    slug: "renovierung",
    title: "Renovierung",
    metaTitle: "Renovierung München – Haus & Wohnung modernisieren | Renodex",
    metaDescription: "Renovierung in München und Umgebung (25 km Radius): Malerarbeiten, Böden, Türen und mehr aus einer Hand – mit Renodex.",
    heroFrage: "Renovierung oder Sanierung – wo liegt der Unterschied?",
    heroLead: "Eine Renovierung erneuert Oberflächen und Ausstattung, ohne in die Bausubstanz einzugreifen – etwa Malerarbeiten, Böden oder Türen. Renodex übernimmt Renovierungen als eigenständiges Vorhaben oder als Teil einer größeren Sanierung.",
    problemUeberschrift: "Mehrere kleine Gewerke, ein überschaubares Budget",
    problemText: "Bei einer Renovierung sollen oft mehrere Räume gleichzeitig aufgefrischt werden – neue Farbe, neue Böden, vielleicht neue Türen. Für jedes Gewerk einen eigenen Handwerker zu finden, kostet Zeit, die bei einem überschaubaren Vorhaben oft in keinem Verhältnis zum Aufwand steht.",
    loesungUeberschrift: "Renovierung aus einer Hand, ohne Umwege",
    loesungPunkte: [
      "Malerarbeiten, Böden und Türen aus einer Beauftragung",
      "Ein Termin für die Besichtigung, ein Angebot für alle Arbeiten",
      "Auf Wunsch Kombination mit Elektro- oder Sanitärarbeiten",
      "Klare Absprache zu Umfang und Zeitrahmen",
    ],
    ausEinerHandText: "Auch kleinere Renovierungen profitieren vom Prinzip aus einer Hand: Renodex bündelt die benötigten Gewerke, statt mehrere Einzelaufträge zu vergeben.",
    faqFrage: "Ab welchem Umfang lohnt sich eine Renovierung durch Renodex?",
    faqAntwort: "Renodex übernimmt sowohl einzelne Räume als auch mehrere Gewerke im Verbund. Ein kurzes Gespräch zum Vorhaben zeigt, ob sich eine gebündelte Beauftragung lohnt.",
  },
  {
    slug: "badsanierung",
    title: "Badsanierung",
    metaTitle: "Badsanierung München – Bad komplett erneuern | Renodex",
    metaDescription: "Badsanierung in München und Umgebung: Sanitär, Fliesen und Elektro aus einer Hand – mit Renodex.",
    heroFrage: "Was macht eine Badsanierung aufwendig?",
    heroLead: "Ein Bad vereint mehrere Gewerke auf kleinem Raum: Sanitärinstallation, Elektrik, Fliesen und oft auch Bodenaufbau. Renodex plant und koordiniert diese Gewerke gemeinsam, damit die Arbeiten ineinandergreifen statt sich zu verzögern.",
    problemUeberschrift: "Viele Gewerke auf engem Raum, hohe Feuchtigkeitsanforderungen",
    problemText: "Beim Bad treffen Sanitär, Elektrik und Fliesenarbeiten auf engstem Raum aufeinander – wird ein Gewerk falsch terminiert, verzögert das die anderen unmittelbar. Zusätzlich verlangen Feuchträume eine fachgerechte Abdichtung, die im Nachhinein kaum korrigierbar ist.",
    loesungUeberschrift: "Sanitär, Elektro und Fliesen in einem Bauablauf",
    loesungPunkte: [
      "Abgestimmte Reihenfolge von Rohbau, Sanitär und Elektro",
      "Fachgerechte Abdichtung nach aktuellem Stand der Technik",
      "Ein Ansprechpartner für den gesamten Bauablauf im Bad",
      "Planung barrierearmer Lösungen auf Wunsch",
    ],
    ausEinerHandText: "Eine Badsanierung ist häufig Teil einer größeren Wohnungs- oder Haussanierung – Renodex bindet sie nahtlos in das Gesamtvorhaben ein.",
    faqFrage: "Wie lange dauert eine Badsanierung?",
    faqAntwort: "Je nach Größe und Umfang der Arbeiten dauert eine Badsanierung typischerweise mehrere Wochen. Der genaue Zeitrahmen wird nach der Besichtigung festgelegt.",
  },
  {
    slug: "bodenverlegung",
    title: "Bodenverlegung",
    metaTitle: "Bodenverlegung München – Böden fachgerecht verlegen | Renodex",
    metaDescription: "Bodenverlegung in München und Umgebung: fachgerechte Verlegung als Teil von Sanierung und Renovierung – mit Renodex.",
    heroFrage: "Worauf kommt es bei der Bodenverlegung an?",
    heroLead: "Ein neuer Boden ist mehr als nur die sichtbare Oberfläche – der Unterbau entscheidet über Langlebigkeit und Wohnqualität. Renodex verlegt Böden fachgerecht, abgestimmt auf Raum, Nutzung und vorhandenen Unterbau.",
    problemUeberschrift: "Unebener Unterbau, falsche Feuchtigkeitswerte, sichtbare Mängel später",
    problemText: "Wird ein Boden ohne fachgerechte Vorbereitung des Unterbaus verlegt, zeigen sich Mängel oft erst Monate später – Fugen öffnen sich, der Boden arbeitet, oder es bildet sich Feuchtigkeit unter dem Belag.",
    loesungUeberschrift: "Verlegung mit geprüftem Unterbau",
    loesungPunkte: [
      "Prüfung von Estrich und Feuchtigkeit vor der Verlegung",
      "Fachgerechte Verlegung nach Herstellervorgaben",
      "Abstimmung mit Heizungs- und Elektroarbeiten im selben Raum",
      "Beratung zur passenden Bodenart je nach Nutzung",
    ],
    ausEinerHandText: "Bodenverlegung wird bei Renodex meist gemeinsam mit Sanitär-, Heizungs- oder Malerarbeiten im selben Bauabschnitt koordiniert.",
    faqFrage: "Welche Bodenarten verlegt Renodex?",
    faqAntwort: "Renodex berät zur passenden Bodenart abhängig von Raum, Nutzung und Budget und übernimmt die fachgerechte Verlegung als Teil der Sanierung.",
  },
  {
    slug: "malerarbeiten-fassade",
    title: "Malerarbeiten und Fassade",
    metaTitle: "Malerarbeiten & Fassade München – innen und außen | Renodex",
    metaDescription: "Malerarbeiten und Fassadenanstrich in München und Umgebung: innen und außen aus einer Hand – mit Renodex.",
    heroFrage: "Was ist bei Malerarbeiten und Fassadenanstrich zu beachten?",
    heroLead: "Ob Innenräume oder Fassade – ein sauberes Ergebnis hängt an der Vorbereitung des Untergrunds mindestens so sehr wie am Anstrich selbst. Renodex übernimmt Malerarbeiten innen und außen als eigenständiges Vorhaben oder im Rahmen einer Sanierung.",
    problemUeberschrift: "Untergrund, Witterung und Termine passen selten von allein zusammen",
    problemText: "Innenanstriche müssen sich in den Bauablauf anderer Gewerke einfügen, Fassadenarbeiten hängen zusätzlich vom Wetter ab. Ohne Abstimmung verzögert sich am Ende der gesamte Zeitplan der Sanierung.",
    loesungUeberschrift: "Malerarbeiten im Bauablauf mitgeplant",
    loesungPunkte: [
      "Untergrundvorbereitung nach Zustand der Wände",
      "Terminierung im Zusammenspiel mit anderen Gewerken",
      "Fassadenanstrich mit Blick auf Witterung und Dämmung",
      "Farbberatung auf Wunsch",
    ],
    ausEinerHandText: "Malerarbeiten sind oft der letzte Schritt einer Sanierung – Renodex terminiert sie so, dass sie nahtlos an die vorherigen Gewerke anschließen.",
    faqFrage: "Übernimmt Renodex auch reine Fassadenarbeiten ohne Innensanierung?",
    faqAntwort: "Ja, Fassadenanstrich und Malerarbeiten sind auch als eigenständiger Auftrag möglich, unabhängig von einer größeren Sanierung.",
  },
  {
    slug: "dachdecker",
    title: "Dachdeckerarbeiten",
    metaTitle: "Dachdecker München – Dacharbeiten als Teil der Sanierung | Renodex",
    metaDescription: "Dachdeckerarbeiten in München und Umgebung: als Teil der Komplettsanierung von Haus und Wohnung – mit Renodex.",
    heroFrage: "Wann werden Dachdeckerarbeiten Teil einer Sanierung?",
    heroLead: "Ein Dach beeinflusst die gesamte Bausubstanz darunter – undichte Stellen oder eine veraltete Eindeckung wirken sich langfristig auf Dämmung und Innenräume aus. Renodex bindet Dachdeckerarbeiten in die Gesamtplanung einer Sanierung ein.",
    problemUeberschrift: "Ein Dachproblem betrifft selten nur das Dach",
    problemText: "Feuchtigkeit vom Dach zeigt sich oft erst an der Decke der obersten Etage – zu diesem Zeitpunkt ist meist schon mehr betroffen als nur die Eindeckung. Wird das Dach isoliert vom restlichen Sanierungsvorhaben betrachtet, entstehen doppelte Arbeiten.",
    loesungUeberschrift: "Dach im Zusammenhang mit der Gesamtsanierung",
    loesungPunkte: [
      "Zustandsprüfung des Dachs im Rahmen der Sanierungsplanung",
      "Abstimmung mit Dämmung und Innenausbau",
      "Koordination mit Spenglerarbeiten für Rinnen und Anschlüsse",
      "Einbindung in den Gesamtzeitplan der Sanierung",
    ],
    ausEinerHandText: "Dachdeckerarbeiten sind bei Renodex kein isoliertes Gewerk, sondern Teil der Komplettsanierung aus einer Hand – abgestimmt mit allen anderen beteiligten Gewerken.",
    faqFrage: "Übernimmt Renodex auch reine Dachreparaturen ohne Gesamtsanierung?",
    faqAntwort: "Dachdeckerarbeiten sind bei Renodex in der Regel Teil einer größeren Sanierung. Der konkrete Umfang wird im persönlichen Gespräch geklärt.",
  },
  {
    slug: "spengler",
    title: "Spenglerarbeiten",
    metaTitle: "Spengler München – Spenglerarbeiten am Bau | Renodex",
    metaDescription: "Spenglerarbeiten in München und Umgebung: Dachrinnen, Fallrohre und Blecharbeiten als Teil der Sanierung – mit Renodex.",
    heroFrage: "Was gehört zu Spenglerarbeiten am Haus?",
    heroLead: "Spenglerarbeiten sichern die Entwässerung und die Anschlüsse am Dach – Dachrinnen, Fallrohre und Blechverkleidungen. Renodex führt Spenglerarbeiten meist im Zusammenhang mit Dachdecker- oder Fassadenarbeiten aus.",
    problemUeberschrift: "Vernachlässigte Entwässerung führt zu Folgeschäden",
    problemText: "Undichte oder verstopfte Dachrinnen leiten Wasser nicht ab, sondern an die Fassade oder ins Mauerwerk – ein Problem, das oft erst bemerkt wird, wenn bereits Feuchtigkeitsschäden entstanden sind.",
    loesungUeberschrift: "Spenglerarbeiten im Zusammenspiel mit Dach und Fassade",
    loesungPunkte: [
      "Prüfung und Erneuerung von Dachrinnen und Fallrohren",
      "Blechanschlüsse fachgerecht an Dach und Fassade",
      "Abstimmung mit Dachdecker- und Malerarbeiten",
      "Vorbeugung gegen Feuchtigkeitsschäden am Mauerwerk",
    ],
    ausEinerHandText: "Spenglerarbeiten werden bei Renodex gemeinsam mit Dachdecker- und Fassadenarbeiten geplant, statt als isolierter Einzelauftrag.",
    faqFrage: "Sind Spenglerarbeiten auch ohne Dachsanierung möglich?",
    faqAntwort: "Ja, etwa bei der reinen Erneuerung von Dachrinnen oder Fallrohren. Renodex prüft den konkreten Bedarf vor Ort.",
  },
  {
    slug: "mauerwerksabdichtung",
    title: "Mauerwerksabdichtung",
    metaTitle: "Mauerwerksabdichtung München – gegen Feuchtigkeit | Renodex",
    metaDescription: "Mauerwerksabdichtung in München und Umgebung: gegen aufsteigende und seitliche Feuchtigkeit – mit Renodex.",
    heroFrage: "Woran erkennt man feuchtes Mauerwerk?",
    heroLead: "Feuchtigkeit im Mauerwerk zeigt sich häufig durch Salzausblühungen, abplatzenden Putz oder muffigen Geruch im Keller. Renodex prüft die Ursache und führt eine fachgerechte Abdichtung durch.",
    problemUeberschrift: "Feuchtigkeit im Mauerwerk bleibt lange unbemerkt",
    problemText: "Aufsteigende oder seitlich eindringende Feuchtigkeit schädigt das Mauerwerk oft über Jahre, bevor sichtbare Schäden entstehen. Wird die Ursache nicht behoben, wirkt jede oberflächliche Reparatur nur kurzfristig.",
    loesungUeberschrift: "Ursachenanalyse vor der Abdichtung",
    loesungPunkte: [
      "Prüfung der Feuchtigkeitsursache vor Beginn der Arbeiten",
      "Fachgerechte Horizontal- und Vertikalabdichtung",
      "Abstimmung mit Kellersanierung, falls betroffen",
      "Langfristige Lösung statt oberflächlicher Reparatur",
    ],
    ausEinerHandText: "Mauerwerksabdichtung ist oft der erste Schritt vor einer Kellersanierung oder Innenraumrenovierung – Renodex plant sie entsprechend in die Gesamtsanierung ein.",
    faqFrage: "Wie erkennt man, ob eine Mauerwerksabdichtung nötig ist?",
    faqAntwort: "Typische Anzeichen sind Feuchtigkeitsflecken, abblätternder Putz oder Salzausblühungen an Kellerwänden. Eine Besichtigung vor Ort klärt die genaue Ursache.",
  },
  {
    slug: "asbestsanierung",
    title: "Asbestsanierung",
    metaTitle: "Asbestsanierung München – fachgerechte Entfernung | Renodex",
    metaDescription: "Asbestsanierung in München und Umgebung: fachgerechte und vorschriftsgemäße Entfernung – mit Renodex.",
    heroFrage: "Wann ist eine Asbestsanierung notwendig?",
    heroLead: "In Gebäuden aus der Bauzeit vor 1993 können asbesthaltige Materialien verbaut sein, etwa in Bodenbelägen, Dachplatten oder Rohrisolierungen. Renodex führt die Entfernung fachgerecht und nach den geltenden Vorschriften durch.",
    problemUeberschrift: "Ungeprüfte Sanierung bei Verdacht auf Asbest ist ein Risiko",
    problemText: "Wird bei Sanierungsarbeiten in älteren Gebäuden asbesthaltiges Material unsachgemäß entfernt oder beschädigt, können Fasern freigesetzt werden. Das betrifft nicht nur die Baustelle selbst, sondern auch angrenzende Bereiche.",
    loesungUeberschrift: "Fachgerechte Entfernung nach Vorschrift",
    loesungPunkte: [
      "Prüfung auf asbesthaltige Materialien vor Sanierungsbeginn",
      "Fachgerechte, vorschriftsgemäße Entfernung",
      "Sichere Entsorgung nach geltenden Bestimmungen",
      "Einbindung in den Gesamtablauf der Sanierung",
    ],
    ausEinerHandText: "Eine Asbestsanierung geht bei älteren Gebäuden häufig einer größeren Sanierung voraus – Renodex koordiniert sie im Vorfeld der weiteren Gewerke.",
    faqFrage: "Woran erkennt man, ob Asbest verbaut ist?",
    faqAntwort: "Eine sichere Einschätzung ist ohne fachliche Prüfung meist nicht möglich, insbesondere bei Gebäuden aus der Bauzeit vor 1993. Renodex berät zum weiteren Vorgehen.",
  },
  {
    slug: "tueren",
    title: "Türen",
    metaTitle: "Türen München – Einbau und Austausch | Renodex",
    metaDescription: "Türen einbauen und austauschen in München und Umgebung: als Teil von Sanierung und Renovierung – mit Renodex.",
    heroFrage: "Wann lohnt sich der Austausch von Türen?",
    heroLead: "Alte Türen beeinträchtigen oft Dämmung, Schallschutz und Optik gleichermaßen. Renodex tauscht Innen- und Haustüren fachgerecht aus, passend zum jeweiligen Sanierungsvorhaben.",
    problemUeberschrift: "Alte Türen schließen schlecht, isolieren kaum",
    problemText: "Verzogene Zargen, undichte Dichtungen oder veraltete Beschläge sorgen dafür, dass Türen weder gut schließen noch ausreichend dämmen – ein Detail, das bei einer Sanierung leicht übersehen wird.",
    loesungUeberschrift: "Türeinbau abgestimmt auf die Sanierung",
    loesungPunkte: [
      "Fachgerechter Einbau von Innen- und Haustüren",
      "Abstimmung mit Boden- und Malerarbeiten",
      "Beratung zu Schall- und Wärmedämmung",
      "Passgenauer Einbau bei unregelmäßigen Bestandsmaßen",
    ],
    ausEinerHandText: "Der Türaustausch wird bei Renodex meist gemeinsam mit Boden- oder Malerarbeiten im selben Bauabschnitt eingeplant.",
    faqFrage: "Tauscht Renodex auch einzelne Türen ohne Gesamtsanierung aus?",
    faqAntwort: "Ja, der Austausch einzelner Türen ist auch unabhängig von einer größeren Sanierung möglich.",
  },
  {
    slug: "elektroinstallation",
    title: "Elektroinstallation",
    metaTitle: "Elektroinstallation München – Elektro bei der Sanierung | Renodex",
    metaDescription: "Elektroinstallation in München und Umgebung: Sanierung veralteter Elektrik als Teil der Komplettsanierung – mit Renodex.",
    heroFrage: "Wann muss die Elektroinstallation erneuert werden?",
    heroLead: "Veraltete Elektroinstallationen erfüllen oft weder aktuelle Sicherheitsanforderungen noch den Strombedarf moderner Haushalte. Renodex erneuert die Elektrik als eigenständiges Vorhaben oder im Rahmen einer Komplettsanierung.",
    problemUeberschrift: "Veraltete Elektrik trifft auf gestiegenen Strombedarf",
    problemText: "Viele Bestandsgebäude verfügen noch über Elektroinstallationen, die für den heutigen Bedarf an Steckdosen, Beleuchtung und Haushaltsgeräten nicht ausgelegt sind – ein Sicherheitsrisiko und ein Komfortproblem zugleich.",
    loesungUeberschrift: "Elektroinstallation nach aktuellem Bedarf",
    loesungPunkte: [
      "Prüfung der bestehenden Elektroinstallation",
      "Erneuerung nach aktuellem Sicherheitsstandard",
      "Planung ausreichender Steckdosen und Anschlüsse",
      "Abstimmung mit Wärmepumpe und Photovoltaik, falls geplant",
    ],
    ausEinerHandText: "Elektroarbeiten sind bei nahezu jeder Sanierung beteiligt – Renodex plant sie von Anfang an mit den übrigen Gewerken zusammen.",
    faqFrage: "Wird bei jeder Sanierung die komplette Elektrik erneuert?",
    faqAntwort: "Nicht zwingend – der Umfang hängt vom Zustand der bestehenden Installation ab. Eine Prüfung vor Ort zeigt, ob eine Teil- oder Komplett­erneuerung sinnvoll ist.",
  },
  {
    slug: "sanitaer",
    title: "Sanitär",
    metaTitle: "Sanitär München – Wasserinstallation bei der Sanierung | Renodex",
    metaDescription: "Sanitär und Wasserinstallation in München und Umgebung: als Teil von Badsanierung und Komplettsanierung – mit Renodex.",
    heroFrage: "Was umfasst eine Sanitärinstallation bei der Sanierung?",
    heroLead: "Zur Sanitärinstallation gehören Wasserleitungen, Abwasserführung und die Anschlüsse für Bad und Küche. Renodex erneuert Sanitärinstallationen fachgerecht, meist im Zusammenhang mit einer Badsanierung.",
    problemUeberschrift: "Alte Leitungen bergen Risiken, die man nicht sieht",
    problemText: "Veraltete Wasserleitungen können korrodieren oder undicht werden, ohne dass es von außen erkennbar ist – bis ein Wasserschaden entsteht. Bei einer Sanierung ist das ein Punkt, der leicht übersehen wird, wenn nur die sichtbare Ausstattung erneuert wird.",
    loesungUeberschrift: "Sanitärinstallation als Teil der Gesamtplanung",
    loesungPunkte: [
      "Prüfung des Zustands vorhandener Leitungen",
      "Fachgerechte Erneuerung von Wasser- und Abwasserleitungen",
      "Abstimmung mit Badsanierung und Bodenverlegung",
      "Anschluss neuer Sanitärobjekte nach aktuellem Standard",
    ],
    ausEinerHandText: "Sanitärarbeiten sind bei Renodex eng mit Badsanierung, Heizung und Bodenverlegung verzahnt – alles aus einer Planung.",
    faqFrage: "Muss bei einer Badsanierung immer die komplette Sanitärinstallation erneuert werden?",
    faqAntwort: "Das hängt vom Alter und Zustand der vorhandenen Leitungen ab. Eine Prüfung vor Ort zeigt, was tatsächlich erneuert werden muss.",
  },
  {
    slug: "heizung",
    title: "Heizung",
    metaTitle: "Heizung München – Heizungsinstallation & Austausch | Renodex",
    metaDescription: "Heizungsinstallation in München und Umgebung: Austausch und Modernisierung als Teil der Sanierung – mit Renodex.",
    heroFrage: "Wann lohnt sich der Austausch der Heizung?",
    heroLead: "Eine veraltete Heizung arbeitet meist weniger effizient als moderne Systeme und verursacht dadurch höhere laufende Kosten. Renodex prüft den Zustand der bestehenden Heizung und plant den Austausch oder die Modernisierung.",
    problemUeberschrift: "Alte Heizung, steigende Kosten, unklare Alternativen",
    problemText: "Viele Eigentümer wissen, dass ihre Heizung nicht mehr zeitgemäß ist, aber nicht, welche Alternative – etwa eine Wärmepumpe oder eine moderne Gasheizung – für ihr Gebäude sinnvoll ist.",
    loesungUeberschrift: "Heizungsmodernisierung mit fachlicher Beratung",
    loesungPunkte: [
      "Prüfung der bestehenden Heizungsanlage",
      "Beratung zu passenden Alternativen für das jeweilige Gebäude",
      "Fachgerechte Installation und Anschluss",
      "Abstimmung mit Sanitär- und Elektroarbeiten",
    ],
    ausEinerHandText: "Ein Heizungstausch wird bei Renodex oft gemeinsam mit Sanitär- und Elektroarbeiten geplant, insbesondere wenn eine Wärmepumpe vorgesehen ist.",
    faqFrage: "Berät Renodex auch zur Wärmepumpe als Alternative?",
    faqAntwort: "Ja, Renodex prüft, ob eine Wärmepumpe für das jeweilige Gebäude eine sinnvolle Alternative zur bestehenden Heizung ist.",
  },
  {
    slug: "waermepumpe",
    title: "Wärmepumpe",
    metaTitle: "Wärmepumpe München – Installation & Beratung | Renodex",
    metaDescription: "Wärmepumpe in München und Umgebung: Beratung und Installation als Teil der Heizungsmodernisierung – mit Renodex.",
    heroFrage: "Für welche Gebäude eignet sich eine Wärmepumpe?",
    heroLead: "Eine Wärmepumpe eignet sich nicht für jedes Gebäude gleichermaßen – Dämmstandard, vorhandene Heizflächen und die bauliche Situation spielen eine Rolle. Renodex prüft die Eignung vor Ort und berät ehrlich, auch wenn eine Alternative sinnvoller ist.",
    problemUeberschrift: "Viele Informationen, wenig Klarheit für das eigene Gebäude",
    problemText: "Zur Wärmepumpe kursieren viele allgemeine Aussagen, die nicht auf jedes Gebäude zutreffen. Ob sich eine Wärmepumpe im konkreten Fall lohnt, hängt von individuellen Faktoren ab, die eine pauschale Aussage nicht beantworten kann.",
    loesungUeberschrift: "Individuelle Prüfung statt pauschaler Empfehlung",
    loesungPunkte: [
      "Prüfung von Dämmstandard und vorhandenen Heizflächen",
      "Ehrliche Einschätzung, ob eine Wärmepumpe sinnvoll ist",
      "Fachgerechte Installation bei geeigneten Gebäuden",
      "Abstimmung mit Elektro- und Sanitärarbeiten",
    ],
    ausEinerHandText: "Die Installation einer Wärmepumpe wird bei Renodex mit den Elektro- und Sanitärarbeiten der Sanierung zusammen geplant.",
    faqFrage: "Ist eine Wärmepumpe auch in einem Altbau sinnvoll?",
    faqAntwort: "Das hängt vom Dämmstandard und den vorhandenen Heizflächen ab. Eine Prüfung vor Ort zeigt, ob eine Wärmepumpe im konkreten Gebäude sinnvoll ist oder eine andere Lösung passender ist.",
  },
  {
    slug: "photovoltaik",
    title: "Photovoltaik",
    metaTitle: "Photovoltaik München – Installation & Beratung | Renodex",
    metaDescription: "Photovoltaik in München und Umgebung: Beratung und Installation als Teil der Sanierung – mit Renodex.",
    heroFrage: "Lohnt sich eine Photovoltaikanlage für jedes Dach?",
    heroLead: "Die Eignung eines Dachs für Photovoltaik hängt von Ausrichtung, Neigung, Verschattung und Zustand der Dachfläche ab. Renodex prüft diese Faktoren vor Ort, bevor eine Empfehlung ausgesprochen wird.",
    problemUeberschrift: "Nicht jedes Dach ist gleich gut geeignet",
    problemText: "Photovoltaik wird oft pauschal empfohlen, ohne die konkrete Dachsituation zu berücksichtigen – Ausrichtung, Verschattung durch Bäume oder Nachbargebäude und der Zustand der Dacheindeckung entscheiden aber über den tatsächlichen Ertrag.",
    loesungUeberschrift: "Prüfung vor Empfehlung",
    loesungPunkte: [
      "Prüfung von Ausrichtung, Neigung und Verschattung",
      "Einschätzung des Zustands der Dacheindeckung vor Installation",
      "Abstimmung mit Elektroinstallation und Wärmepumpe",
      "Koordination mit Dachdeckerarbeiten, falls das Dach zuerst erneuert werden muss",
    ],
    ausEinerHandText: "Photovoltaik wird bei Renodex im Zusammenhang mit Dach, Elektro und Wärmepumpe geplant – nicht isoliert von der übrigen Sanierung.",
    faqFrage: "Muss das Dach vor einer Photovoltaikanlage erneuert werden?",
    faqAntwort: "Das hängt vom Zustand der bestehenden Eindeckung ab. Bei einem sanierungsbedürftigen Dach empfiehlt sich die Erneuerung vor der Installation der Anlage.",
  },
];
